// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	protocol "github.com/hoywu/expo-ota/server/api/protocol/internal/handler/protocol"
	"github.com/hoywu/expo-ota/server/api/protocol/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/:appSlug/manifest",
				Handler: protocol.ManifestHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:appSlug/events",
				Handler: protocol.EventsHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/apps"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/healthz",
				Handler: protocol.HealthzHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/readyz",
				Handler: protocol.ReadyzHandler(serverCtx),
			},
		},
	)
}
