// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/apitokensmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/apitokensmodel.go -destination=db/models/apitokensmodel_mock.go -package=models -aux_files=models=db/models/apitokensmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockApiTokensModel is a mock of ApiTokensModel interface.
type MockApiTokensModel struct {
	ctrl     *gomock.Controller
	recorder *MockApiTokensModelMockRecorder
	isgomock struct{}
}

// MockApiTokensModelMockRecorder is the mock recorder for MockApiTokensModel.
type MockApiTokensModelMockRecorder struct {
	mock *MockApiTokensModel
}

// NewMockApiTokensModel creates a new mock instance.
func NewMockApiTokensModel(ctrl *gomock.Controller) *MockApiTokensModel {
	mock := &MockApiTokensModel{ctrl: ctrl}
	mock.recorder = &MockApiTokensModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApiTokensModel) EXPECT() *MockApiTokensModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockApiTokensModel) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockApiTokensModelMockRecorder) Delete(ctx, id any) *MockApiTokensModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockApiTokensModel)(nil).Delete), ctx, id)
	return &MockApiTokensModelDeleteCall{Call: call}
}

// MockApiTokensModelDeleteCall wrap *gomock.Call
type MockApiTokensModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiTokensModelDeleteCall) Return(arg0 error) *MockApiTokensModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiTokensModelDeleteCall) Do(f func(context.Context, string) error) *MockApiTokensModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiTokensModelDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockApiTokensModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindAllByAppId mocks base method.
func (m *MockApiTokensModel) FindAllByAppId(ctx context.Context, appId string) ([]*ApiTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByAppId", ctx, appId)
	ret0, _ := ret[0].([]*ApiTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByAppId indicates an expected call of FindAllByAppId.
func (mr *MockApiTokensModelMockRecorder) FindAllByAppId(ctx, appId any) *MockApiTokensModelFindAllByAppIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByAppId", reflect.TypeOf((*MockApiTokensModel)(nil).FindAllByAppId), ctx, appId)
	return &MockApiTokensModelFindAllByAppIdCall{Call: call}
}

// MockApiTokensModelFindAllByAppIdCall wrap *gomock.Call
type MockApiTokensModelFindAllByAppIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiTokensModelFindAllByAppIdCall) Return(arg0 []*ApiTokens, arg1 error) *MockApiTokensModelFindAllByAppIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiTokensModelFindAllByAppIdCall) Do(f func(context.Context, string) ([]*ApiTokens, error)) *MockApiTokensModelFindAllByAppIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiTokensModelFindAllByAppIdCall) DoAndReturn(f func(context.Context, string) ([]*ApiTokens, error)) *MockApiTokensModelFindAllByAppIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockApiTokensModel) FindOne(ctx context.Context, id string) (*ApiTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*ApiTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockApiTokensModelMockRecorder) FindOne(ctx, id any) *MockApiTokensModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockApiTokensModel)(nil).FindOne), ctx, id)
	return &MockApiTokensModelFindOneCall{Call: call}
}

// MockApiTokensModelFindOneCall wrap *gomock.Call
type MockApiTokensModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiTokensModelFindOneCall) Return(arg0 *ApiTokens, arg1 error) *MockApiTokensModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiTokensModelFindOneCall) Do(f func(context.Context, string) (*ApiTokens, error)) *MockApiTokensModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiTokensModelFindOneCall) DoAndReturn(f func(context.Context, string) (*ApiTokens, error)) *MockApiTokensModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByTokenHash mocks base method.
func (m *MockApiTokensModel) FindOneByTokenHash(ctx context.Context, tokenHash string) (*ApiTokens, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByTokenHash", ctx, tokenHash)
	ret0, _ := ret[0].(*ApiTokens)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByTokenHash indicates an expected call of FindOneByTokenHash.
func (mr *MockApiTokensModelMockRecorder) FindOneByTokenHash(ctx, tokenHash any) *MockApiTokensModelFindOneByTokenHashCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByTokenHash", reflect.TypeOf((*MockApiTokensModel)(nil).FindOneByTokenHash), ctx, tokenHash)
	return &MockApiTokensModelFindOneByTokenHashCall{Call: call}
}

// MockApiTokensModelFindOneByTokenHashCall wrap *gomock.Call
type MockApiTokensModelFindOneByTokenHashCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiTokensModelFindOneByTokenHashCall) Return(arg0 *ApiTokens, arg1 error) *MockApiTokensModelFindOneByTokenHashCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiTokensModelFindOneByTokenHashCall) Do(f func(context.Context, string) (*ApiTokens, error)) *MockApiTokensModelFindOneByTokenHashCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiTokensModelFindOneByTokenHashCall) DoAndReturn(f func(context.Context, string) (*ApiTokens, error)) *MockApiTokensModelFindOneByTokenHashCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockApiTokensModel) Insert(ctx context.Context, data *ApiTokens) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockApiTokensModelMockRecorder) Insert(ctx, data any) *MockApiTokensModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockApiTokensModel)(nil).Insert), ctx, data)
	return &MockApiTokensModelInsertCall{Call: call}
}

// MockApiTokensModelInsertCall wrap *gomock.Call
type MockApiTokensModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiTokensModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockApiTokensModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiTokensModelInsertCall) Do(f func(context.Context, *ApiTokens) (sql.Result, error)) *MockApiTokensModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiTokensModelInsertCall) DoAndReturn(f func(context.Context, *ApiTokens) (sql.Result, error)) *MockApiTokensModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockApiTokensModel) Update(ctx context.Context, data *ApiTokens) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockApiTokensModelMockRecorder) Update(ctx, data any) *MockApiTokensModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockApiTokensModel)(nil).Update), ctx, data)
	return &MockApiTokensModelUpdateCall{Call: call}
}

// MockApiTokensModelUpdateCall wrap *gomock.Call
type MockApiTokensModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiTokensModelUpdateCall) Return(arg0 error) *MockApiTokensModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiTokensModelUpdateCall) Do(f func(context.Context, *ApiTokens) error) *MockApiTokensModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiTokensModelUpdateCall) DoAndReturn(f func(context.Context, *ApiTokens) error) *MockApiTokensModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockApiTokensModel) withSession(session sqlx.Session) ApiTokensModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(ApiTokensModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockApiTokensModelMockRecorder) withSession(session any) *MockApiTokensModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockApiTokensModel)(nil).withSession), session)
	return &MockApiTokensModelwithSessionCall{Call: call}
}

// MockApiTokensModelwithSessionCall wrap *gomock.Call
type MockApiTokensModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockApiTokensModelwithSessionCall) Return(arg0 ApiTokensModel) *MockApiTokensModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockApiTokensModelwithSessionCall) Do(f func(sqlx.Session) ApiTokensModel) *MockApiTokensModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockApiTokensModelwithSessionCall) DoAndReturn(f func(sqlx.Session) ApiTokensModel) *MockApiTokensModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
