// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/lib/pq"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	apiTokensFieldNames          = builder.RawFieldNames(&ApiTokens{}, true)
	apiTokensRows                = strings.Join(apiTokensFieldNames, ",")
	apiTokensRowsExpectAutoSet   = strings.Join(stringx.Remove(apiTokensFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	apiTokensRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(apiTokensFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	apiTokensModel interface {
		Insert(ctx context.Context, data *ApiTokens) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*ApiTokens, error)
		FindOneByTokenHash(ctx context.Context, tokenHash []byte) (*ApiTokens, error)
		Update(ctx context.Context, data *ApiTokens) error
		Delete(ctx context.Context, id string) error
	}

	defaultApiTokensModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ApiTokens struct {
		Id         string         `db:"id"`
		AppId      string         `db:"app_id"`
		CreatedBy  string         `db:"created_by"`
		Name       string         `db:"name"`
		TokenHash  []byte         `db:"token_hash"`
		Scopes     pq.StringArray `db:"scopes"`
		LastUsedAt sql.NullTime   `db:"last_used_at"`
		ExpiresAt  sql.NullTime   `db:"expires_at"`
		CreatedAt  time.Time      `db:"created_at"`
		RevokedAt  sql.NullTime   `db:"revoked_at"`
	}
)

func newApiTokensModel(conn sqlx.SqlConn) *defaultApiTokensModel {
	return &defaultApiTokensModel{
		conn:  conn,
		table: `"public"."api_tokens"`,
	}
}

func (m *defaultApiTokensModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultApiTokensModel) FindOne(ctx context.Context, id string) (*ApiTokens, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", apiTokensRows, m.table)
	var resp ApiTokens
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultApiTokensModel) FindOneByTokenHash(ctx context.Context, tokenHash []byte) (*ApiTokens, error) {
	var resp ApiTokens
	query := fmt.Sprintf("select %s from %s where token_hash = $1 limit 1", apiTokensRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, tokenHash)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultApiTokensModel) Insert(ctx context.Context, data *ApiTokens) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, apiTokensRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.AppId, data.CreatedBy, data.Name, data.TokenHash, data.Scopes, data.LastUsedAt, data.ExpiresAt, data.RevokedAt)
	return ret, err
}

func (m *defaultApiTokensModel) Update(ctx context.Context, newData *ApiTokens) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, apiTokensRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.AppId, newData.CreatedBy, newData.Name, newData.TokenHash, newData.Scopes, newData.LastUsedAt, newData.ExpiresAt, newData.RevokedAt)
	return err
}

func (m *defaultApiTokensModel) tableName() string {
	return m.table
}
