// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/appsmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/appsmodel.go -destination=db/models/appsmodel_mock.go -package=models -aux_files=models=db/models/appsmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockAppsModel is a mock of AppsModel interface.
type MockAppsModel struct {
	ctrl     *gomock.Controller
	recorder *MockAppsModelMockRecorder
	isgomock struct{}
}

// MockAppsModelMockRecorder is the mock recorder for MockAppsModel.
type MockAppsModelMockRecorder struct {
	mock *MockAppsModel
}

// NewMockAppsModel creates a new mock instance.
func NewMockAppsModel(ctrl *gomock.Controller) *MockAppsModel {
	mock := &MockAppsModel{ctrl: ctrl}
	mock.recorder = &MockAppsModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAppsModel) EXPECT() *MockAppsModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAppsModel) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAppsModelMockRecorder) Delete(ctx, id any) *MockAppsModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAppsModel)(nil).Delete), ctx, id)
	return &MockAppsModelDeleteCall{Call: call}
}

// MockAppsModelDeleteCall wrap *gomock.Call
type MockAppsModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppsModelDeleteCall) Return(arg0 error) *MockAppsModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppsModelDeleteCall) Do(f func(context.Context, string) error) *MockAppsModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppsModelDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockAppsModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindAllActive mocks base method.
func (m *MockAppsModel) FindAllActive(ctx context.Context) ([]*Apps, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllActive", ctx)
	ret0, _ := ret[0].([]*Apps)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllActive indicates an expected call of FindAllActive.
func (mr *MockAppsModelMockRecorder) FindAllActive(ctx any) *MockAppsModelFindAllActiveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllActive", reflect.TypeOf((*MockAppsModel)(nil).FindAllActive), ctx)
	return &MockAppsModelFindAllActiveCall{Call: call}
}

// MockAppsModelFindAllActiveCall wrap *gomock.Call
type MockAppsModelFindAllActiveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppsModelFindAllActiveCall) Return(arg0 []*Apps, arg1 error) *MockAppsModelFindAllActiveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppsModelFindAllActiveCall) Do(f func(context.Context) ([]*Apps, error)) *MockAppsModelFindAllActiveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppsModelFindAllActiveCall) DoAndReturn(f func(context.Context) ([]*Apps, error)) *MockAppsModelFindAllActiveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockAppsModel) FindOne(ctx context.Context, id string) (*Apps, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*Apps)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockAppsModelMockRecorder) FindOne(ctx, id any) *MockAppsModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockAppsModel)(nil).FindOne), ctx, id)
	return &MockAppsModelFindOneCall{Call: call}
}

// MockAppsModelFindOneCall wrap *gomock.Call
type MockAppsModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppsModelFindOneCall) Return(arg0 *Apps, arg1 error) *MockAppsModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppsModelFindOneCall) Do(f func(context.Context, string) (*Apps, error)) *MockAppsModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppsModelFindOneCall) DoAndReturn(f func(context.Context, string) (*Apps, error)) *MockAppsModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByAppSlug mocks base method.
func (m *MockAppsModel) FindOneByAppSlug(ctx context.Context, appSlug string) (*Apps, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByAppSlug", ctx, appSlug)
	ret0, _ := ret[0].(*Apps)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByAppSlug indicates an expected call of FindOneByAppSlug.
func (mr *MockAppsModelMockRecorder) FindOneByAppSlug(ctx, appSlug any) *MockAppsModelFindOneByAppSlugCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByAppSlug", reflect.TypeOf((*MockAppsModel)(nil).FindOneByAppSlug), ctx, appSlug)
	return &MockAppsModelFindOneByAppSlugCall{Call: call}
}

// MockAppsModelFindOneByAppSlugCall wrap *gomock.Call
type MockAppsModelFindOneByAppSlugCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppsModelFindOneByAppSlugCall) Return(arg0 *Apps, arg1 error) *MockAppsModelFindOneByAppSlugCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppsModelFindOneByAppSlugCall) Do(f func(context.Context, string) (*Apps, error)) *MockAppsModelFindOneByAppSlugCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppsModelFindOneByAppSlugCall) DoAndReturn(f func(context.Context, string) (*Apps, error)) *MockAppsModelFindOneByAppSlugCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockAppsModel) Insert(ctx context.Context, data *Apps) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockAppsModelMockRecorder) Insert(ctx, data any) *MockAppsModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAppsModel)(nil).Insert), ctx, data)
	return &MockAppsModelInsertCall{Call: call}
}

// MockAppsModelInsertCall wrap *gomock.Call
type MockAppsModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppsModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockAppsModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppsModelInsertCall) Do(f func(context.Context, *Apps) (sql.Result, error)) *MockAppsModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppsModelInsertCall) DoAndReturn(f func(context.Context, *Apps) (sql.Result, error)) *MockAppsModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockAppsModel) Update(ctx context.Context, data *Apps) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAppsModelMockRecorder) Update(ctx, data any) *MockAppsModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAppsModel)(nil).Update), ctx, data)
	return &MockAppsModelUpdateCall{Call: call}
}

// MockAppsModelUpdateCall wrap *gomock.Call
type MockAppsModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppsModelUpdateCall) Return(arg0 error) *MockAppsModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppsModelUpdateCall) Do(f func(context.Context, *Apps) error) *MockAppsModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppsModelUpdateCall) DoAndReturn(f func(context.Context, *Apps) error) *MockAppsModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockAppsModel) withSession(session sqlx.Session) AppsModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(AppsModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockAppsModelMockRecorder) withSession(session any) *MockAppsModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockAppsModel)(nil).withSession), session)
	return &MockAppsModelwithSessionCall{Call: call}
}

// MockAppsModelwithSessionCall wrap *gomock.Call
type MockAppsModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAppsModelwithSessionCall) Return(arg0 AppsModel) *MockAppsModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAppsModelwithSessionCall) Do(f func(sqlx.Session) AppsModel) *MockAppsModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAppsModelwithSessionCall) DoAndReturn(f func(sqlx.Session) AppsModel) *MockAppsModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
