// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	appsFieldNames          = builder.RawFieldNames(&Apps{}, true)
	appsRows                = strings.Join(appsFieldNames, ",")
	appsRowsExpectAutoSet   = strings.Join(stringx.Remove(appsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	appsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(appsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	appsModel interface {
		Insert(ctx context.Context, data *Apps) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Apps, error)
		FindOneByAppSlug(ctx context.Context, appSlug string) (*Apps, error)
		Update(ctx context.Context, data *Apps) error
		Delete(ctx context.Context, id string) error
	}

	defaultAppsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Apps struct {
		Id          string         `db:"id"`
		AppSlug     string         `db:"app_slug"`
		Name        string         `db:"name"`
		Description sql.NullString `db:"description"`
		CreatedAt   time.Time      `db:"created_at"`
		DeletedAt   sql.NullTime   `db:"deleted_at"`
	}
)

func newAppsModel(conn sqlx.SqlConn) *defaultAppsModel {
	return &defaultAppsModel{
		conn:  conn,
		table: `"public"."apps"`,
	}
}

func (m *defaultAppsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAppsModel) FindOne(ctx context.Context, id string) (*Apps, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", appsRows, m.table)
	var resp Apps
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppsModel) FindOneByAppSlug(ctx context.Context, appSlug string) (*Apps, error) {
	var resp Apps
	query := fmt.Sprintf("select %s from %s where app_slug = $1 limit 1", appsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, appSlug)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAppsModel) Insert(ctx context.Context, data *Apps) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5)", m.table, appsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.AppSlug, data.Name, data.Description, data.DeletedAt)
	return ret, err
}

func (m *defaultAppsModel) Update(ctx context.Context, newData *Apps) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, appsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.AppSlug, newData.Name, newData.Description, newData.DeletedAt)
	return err
}

func (m *defaultAppsModel) tableName() string {
	return m.table
}
