// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/assetsmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/assetsmodel.go -destination=db/models/assetsmodel_mock.go -package=models -aux_files=models=db/models/assetsmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockAssetsModel is a mock of AssetsModel interface.
type MockAssetsModel struct {
	ctrl     *gomock.Controller
	recorder *MockAssetsModelMockRecorder
	isgomock struct{}
}

// MockAssetsModelMockRecorder is the mock recorder for MockAssetsModel.
type MockAssetsModelMockRecorder struct {
	mock *MockAssetsModel
}

// NewMockAssetsModel creates a new mock instance.
func NewMockAssetsModel(ctrl *gomock.Controller) *MockAssetsModel {
	mock := &MockAssetsModel{ctrl: ctrl}
	mock.recorder = &MockAssetsModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAssetsModel) EXPECT() *MockAssetsModelMockRecorder {
	return m.recorder
}

// CountOrphanByAppId mocks base method.
func (m *MockAssetsModel) CountOrphanByAppId(ctx context.Context, appId string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountOrphanByAppId", ctx, appId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountOrphanByAppId indicates an expected call of CountOrphanByAppId.
func (mr *MockAssetsModelMockRecorder) CountOrphanByAppId(ctx, appId any) *MockAssetsModelCountOrphanByAppIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountOrphanByAppId", reflect.TypeOf((*MockAssetsModel)(nil).CountOrphanByAppId), ctx, appId)
	return &MockAssetsModelCountOrphanByAppIdCall{Call: call}
}

// MockAssetsModelCountOrphanByAppIdCall wrap *gomock.Call
type MockAssetsModelCountOrphanByAppIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssetsModelCountOrphanByAppIdCall) Return(arg0 int64, arg1 error) *MockAssetsModelCountOrphanByAppIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssetsModelCountOrphanByAppIdCall) Do(f func(context.Context, string) (int64, error)) *MockAssetsModelCountOrphanByAppIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssetsModelCountOrphanByAppIdCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockAssetsModelCountOrphanByAppIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockAssetsModel) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAssetsModelMockRecorder) Delete(ctx, id any) *MockAssetsModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAssetsModel)(nil).Delete), ctx, id)
	return &MockAssetsModelDeleteCall{Call: call}
}

// MockAssetsModelDeleteCall wrap *gomock.Call
type MockAssetsModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssetsModelDeleteCall) Return(arg0 error) *MockAssetsModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssetsModelDeleteCall) Do(f func(context.Context, string) error) *MockAssetsModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssetsModelDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockAssetsModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindAllByIds mocks base method.
func (m *MockAssetsModel) FindAllByIds(ctx context.Context, ids []string) ([]*Assets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByIds", ctx, ids)
	ret0, _ := ret[0].([]*Assets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByIds indicates an expected call of FindAllByIds.
func (mr *MockAssetsModelMockRecorder) FindAllByIds(ctx, ids any) *MockAssetsModelFindAllByIdsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByIds", reflect.TypeOf((*MockAssetsModel)(nil).FindAllByIds), ctx, ids)
	return &MockAssetsModelFindAllByIdsCall{Call: call}
}

// MockAssetsModelFindAllByIdsCall wrap *gomock.Call
type MockAssetsModelFindAllByIdsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssetsModelFindAllByIdsCall) Return(arg0 []*Assets, arg1 error) *MockAssetsModelFindAllByIdsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssetsModelFindAllByIdsCall) Do(f func(context.Context, []string) ([]*Assets, error)) *MockAssetsModelFindAllByIdsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssetsModelFindAllByIdsCall) DoAndReturn(f func(context.Context, []string) ([]*Assets, error)) *MockAssetsModelFindAllByIdsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockAssetsModel) FindOne(ctx context.Context, id string) (*Assets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*Assets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockAssetsModelMockRecorder) FindOne(ctx, id any) *MockAssetsModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockAssetsModel)(nil).FindOne), ctx, id)
	return &MockAssetsModelFindOneCall{Call: call}
}

// MockAssetsModelFindOneCall wrap *gomock.Call
type MockAssetsModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssetsModelFindOneCall) Return(arg0 *Assets, arg1 error) *MockAssetsModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssetsModelFindOneCall) Do(f func(context.Context, string) (*Assets, error)) *MockAssetsModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssetsModelFindOneCall) DoAndReturn(f func(context.Context, string) (*Assets, error)) *MockAssetsModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByAppIdSha256 mocks base method.
func (m *MockAssetsModel) FindOneByAppIdSha256(ctx context.Context, appId, sha256 string) (*Assets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByAppIdSha256", ctx, appId, sha256)
	ret0, _ := ret[0].(*Assets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByAppIdSha256 indicates an expected call of FindOneByAppIdSha256.
func (mr *MockAssetsModelMockRecorder) FindOneByAppIdSha256(ctx, appId, sha256 any) *MockAssetsModelFindOneByAppIdSha256Call {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByAppIdSha256", reflect.TypeOf((*MockAssetsModel)(nil).FindOneByAppIdSha256), ctx, appId, sha256)
	return &MockAssetsModelFindOneByAppIdSha256Call{Call: call}
}

// MockAssetsModelFindOneByAppIdSha256Call wrap *gomock.Call
type MockAssetsModelFindOneByAppIdSha256Call struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssetsModelFindOneByAppIdSha256Call) Return(arg0 *Assets, arg1 error) *MockAssetsModelFindOneByAppIdSha256Call {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssetsModelFindOneByAppIdSha256Call) Do(f func(context.Context, string, string) (*Assets, error)) *MockAssetsModelFindOneByAppIdSha256Call {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssetsModelFindOneByAppIdSha256Call) DoAndReturn(f func(context.Context, string, string) (*Assets, error)) *MockAssetsModelFindOneByAppIdSha256Call {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockAssetsModel) Insert(ctx context.Context, data *Assets) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockAssetsModelMockRecorder) Insert(ctx, data any) *MockAssetsModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAssetsModel)(nil).Insert), ctx, data)
	return &MockAssetsModelInsertCall{Call: call}
}

// MockAssetsModelInsertCall wrap *gomock.Call
type MockAssetsModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssetsModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockAssetsModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssetsModelInsertCall) Do(f func(context.Context, *Assets) (sql.Result, error)) *MockAssetsModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssetsModelInsertCall) DoAndReturn(f func(context.Context, *Assets) (sql.Result, error)) *MockAssetsModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InsertIgnoreConflict mocks base method.
func (m *MockAssetsModel) InsertIgnoreConflict(ctx context.Context, data *Assets) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertIgnoreConflict", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertIgnoreConflict indicates an expected call of InsertIgnoreConflict.
func (mr *MockAssetsModelMockRecorder) InsertIgnoreConflict(ctx, data any) *MockAssetsModelInsertIgnoreConflictCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertIgnoreConflict", reflect.TypeOf((*MockAssetsModel)(nil).InsertIgnoreConflict), ctx, data)
	return &MockAssetsModelInsertIgnoreConflictCall{Call: call}
}

// MockAssetsModelInsertIgnoreConflictCall wrap *gomock.Call
type MockAssetsModelInsertIgnoreConflictCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssetsModelInsertIgnoreConflictCall) Return(arg0 error) *MockAssetsModelInsertIgnoreConflictCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssetsModelInsertIgnoreConflictCall) Do(f func(context.Context, *Assets) error) *MockAssetsModelInsertIgnoreConflictCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssetsModelInsertIgnoreConflictCall) DoAndReturn(f func(context.Context, *Assets) error) *MockAssetsModelInsertIgnoreConflictCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockAssetsModel) Update(ctx context.Context, data *Assets) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAssetsModelMockRecorder) Update(ctx, data any) *MockAssetsModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAssetsModel)(nil).Update), ctx, data)
	return &MockAssetsModelUpdateCall{Call: call}
}

// MockAssetsModelUpdateCall wrap *gomock.Call
type MockAssetsModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssetsModelUpdateCall) Return(arg0 error) *MockAssetsModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssetsModelUpdateCall) Do(f func(context.Context, *Assets) error) *MockAssetsModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssetsModelUpdateCall) DoAndReturn(f func(context.Context, *Assets) error) *MockAssetsModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockAssetsModel) withSession(session sqlx.Session) AssetsModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(AssetsModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockAssetsModelMockRecorder) withSession(session any) *MockAssetsModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockAssetsModel)(nil).withSession), session)
	return &MockAssetsModelwithSessionCall{Call: call}
}

// MockAssetsModelwithSessionCall wrap *gomock.Call
type MockAssetsModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAssetsModelwithSessionCall) Return(arg0 AssetsModel) *MockAssetsModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAssetsModelwithSessionCall) Do(f func(sqlx.Session) AssetsModel) *MockAssetsModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAssetsModelwithSessionCall) DoAndReturn(f func(sqlx.Session) AssetsModel) *MockAssetsModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
