// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	assetsFieldNames          = builder.RawFieldNames(&Assets{}, true)
	assetsRows                = strings.Join(assetsFieldNames, ",")
	assetsRowsExpectAutoSet   = strings.Join(stringx.Remove(assetsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	assetsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(assetsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	assetsModel interface {
		Insert(ctx context.Context, data *Assets) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Assets, error)
		FindOneByAppIdSha256(ctx context.Context, appId string, sha256 []byte) (*Assets, error)
		Update(ctx context.Context, data *Assets) error
		Delete(ctx context.Context, id string) error
	}

	defaultAssetsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Assets struct {
		Id           string         `db:"id"`
		AppId        string         `db:"app_id"`
		Sha256       []byte         `db:"sha256"`
		Sha256B64url string         `db:"sha256_b64url"`
		SizeBytes    int64          `db:"size_bytes"`
		ContentType  string         `db:"content_type"`
		FileExt      sql.NullString `db:"file_ext"`
		StorageKey   string         `db:"storage_key"`
		CreatedAt    time.Time      `db:"created_at"`
	}
)

func newAssetsModel(conn sqlx.SqlConn) *defaultAssetsModel {
	return &defaultAssetsModel{
		conn:  conn,
		table: `"public"."assets"`,
	}
}

func (m *defaultAssetsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAssetsModel) FindOne(ctx context.Context, id string) (*Assets, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", assetsRows, m.table)
	var resp Assets
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAssetsModel) FindOneByAppIdSha256(ctx context.Context, appId string, sha256 []byte) (*Assets, error) {
	var resp Assets
	query := fmt.Sprintf("select %s from %s where app_id = $1 and sha256 = $2 limit 1", assetsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, appId, sha256)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAssetsModel) Insert(ctx context.Context, data *Assets) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, assetsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.AppId, data.Sha256, data.Sha256B64url, data.SizeBytes, data.ContentType, data.FileExt, data.StorageKey)
	return ret, err
}

func (m *defaultAssetsModel) Update(ctx context.Context, newData *Assets) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, assetsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.AppId, newData.Sha256, newData.Sha256B64url, newData.SizeBytes, newData.ContentType, newData.FileExt, newData.StorageKey)
	return err
}

func (m *defaultAssetsModel) tableName() string {
	return m.table
}
