// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	auditLogsFieldNames          = builder.RawFieldNames(&AuditLogs{}, true)
	auditLogsRows                = strings.Join(auditLogsFieldNames, ",")
	auditLogsRowsExpectAutoSet   = strings.Join(stringx.Remove(auditLogsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	auditLogsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(auditLogsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	auditLogsModel interface {
		Insert(ctx context.Context, data *AuditLogs) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AuditLogs, error)
		Update(ctx context.Context, data *AuditLogs) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAuditLogsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	AuditLogs struct {
		Id          int64          `db:"id"`
		AppId       sql.NullString `db:"app_id"`
		ActorUserId sql.NullString `db:"actor_user_id"`
		Action      string         `db:"action"`
		TargetType  sql.NullString `db:"target_type"`
		TargetId    sql.NullString `db:"target_id"`
		RequestId   sql.NullString `db:"request_id"`
		Ip          sql.NullString `db:"ip"`
		UserAgent   sql.NullString `db:"user_agent"`
		Payload     string         `db:"payload"`
		OccurredAt  time.Time      `db:"occurred_at"`
	}
)

func newAuditLogsModel(conn sqlx.SqlConn) *defaultAuditLogsModel {
	return &defaultAuditLogsModel{
		conn:  conn,
		table: `"public"."audit_logs"`,
	}
}

func (m *defaultAuditLogsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultAuditLogsModel) FindOne(ctx context.Context, id int64) (*AuditLogs, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", auditLogsRows, m.table)
	var resp AuditLogs
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAuditLogsModel) Insert(ctx context.Context, data *AuditLogs) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)", m.table, auditLogsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AppId, data.ActorUserId, data.Action, data.TargetType, data.TargetId, data.RequestId, data.Ip, data.UserAgent, data.Payload, data.OccurredAt)
	return ret, err
}

func (m *defaultAuditLogsModel) Update(ctx context.Context, data *AuditLogs) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, auditLogsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.AppId, data.ActorUserId, data.Action, data.TargetType, data.TargetId, data.RequestId, data.Ip, data.UserAgent, data.Payload, data.OccurredAt)
	return err
}

func (m *defaultAuditLogsModel) tableName() string {
	return m.table
}
