// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/auditlogsmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/auditlogsmodel.go -destination=db/models/auditlogsmodel_mock.go -package=models -aux_files=models=db/models/auditlogsmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockAuditLogsModel is a mock of AuditLogsModel interface.
type MockAuditLogsModel struct {
	ctrl     *gomock.Controller
	recorder *MockAuditLogsModelMockRecorder
	isgomock struct{}
}

// MockAuditLogsModelMockRecorder is the mock recorder for MockAuditLogsModel.
type MockAuditLogsModelMockRecorder struct {
	mock *MockAuditLogsModel
}

// NewMockAuditLogsModel creates a new mock instance.
func NewMockAuditLogsModel(ctrl *gomock.Controller) *MockAuditLogsModel {
	mock := &MockAuditLogsModel{ctrl: ctrl}
	mock.recorder = &MockAuditLogsModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditLogsModel) EXPECT() *MockAuditLogsModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockAuditLogsModel) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuditLogsModelMockRecorder) Delete(ctx, id any) *MockAuditLogsModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuditLogsModel)(nil).Delete), ctx, id)
	return &MockAuditLogsModelDeleteCall{Call: call}
}

// MockAuditLogsModelDeleteCall wrap *gomock.Call
type MockAuditLogsModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuditLogsModelDeleteCall) Return(arg0 error) *MockAuditLogsModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuditLogsModelDeleteCall) Do(f func(context.Context, int64) error) *MockAuditLogsModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuditLogsModelDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockAuditLogsModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindManyByAppId mocks base method.
func (m *MockAuditLogsModel) FindManyByAppId(ctx context.Context, appId string, filter AuditLogsFilter) ([]*AuditLogs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindManyByAppId", ctx, appId, filter)
	ret0, _ := ret[0].([]*AuditLogs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindManyByAppId indicates an expected call of FindManyByAppId.
func (mr *MockAuditLogsModelMockRecorder) FindManyByAppId(ctx, appId, filter any) *MockAuditLogsModelFindManyByAppIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindManyByAppId", reflect.TypeOf((*MockAuditLogsModel)(nil).FindManyByAppId), ctx, appId, filter)
	return &MockAuditLogsModelFindManyByAppIdCall{Call: call}
}

// MockAuditLogsModelFindManyByAppIdCall wrap *gomock.Call
type MockAuditLogsModelFindManyByAppIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuditLogsModelFindManyByAppIdCall) Return(arg0 []*AuditLogs, arg1 error) *MockAuditLogsModelFindManyByAppIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuditLogsModelFindManyByAppIdCall) Do(f func(context.Context, string, AuditLogsFilter) ([]*AuditLogs, error)) *MockAuditLogsModelFindManyByAppIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuditLogsModelFindManyByAppIdCall) DoAndReturn(f func(context.Context, string, AuditLogsFilter) ([]*AuditLogs, error)) *MockAuditLogsModelFindManyByAppIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockAuditLogsModel) FindOne(ctx context.Context, id int64) (*AuditLogs, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*AuditLogs)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockAuditLogsModelMockRecorder) FindOne(ctx, id any) *MockAuditLogsModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockAuditLogsModel)(nil).FindOne), ctx, id)
	return &MockAuditLogsModelFindOneCall{Call: call}
}

// MockAuditLogsModelFindOneCall wrap *gomock.Call
type MockAuditLogsModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuditLogsModelFindOneCall) Return(arg0 *AuditLogs, arg1 error) *MockAuditLogsModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuditLogsModelFindOneCall) Do(f func(context.Context, int64) (*AuditLogs, error)) *MockAuditLogsModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuditLogsModelFindOneCall) DoAndReturn(f func(context.Context, int64) (*AuditLogs, error)) *MockAuditLogsModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockAuditLogsModel) Insert(ctx context.Context, data *AuditLogs) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockAuditLogsModelMockRecorder) Insert(ctx, data any) *MockAuditLogsModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockAuditLogsModel)(nil).Insert), ctx, data)
	return &MockAuditLogsModelInsertCall{Call: call}
}

// MockAuditLogsModelInsertCall wrap *gomock.Call
type MockAuditLogsModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuditLogsModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockAuditLogsModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuditLogsModelInsertCall) Do(f func(context.Context, *AuditLogs) (sql.Result, error)) *MockAuditLogsModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuditLogsModelInsertCall) DoAndReturn(f func(context.Context, *AuditLogs) (sql.Result, error)) *MockAuditLogsModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockAuditLogsModel) Update(ctx context.Context, data *AuditLogs) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAuditLogsModelMockRecorder) Update(ctx, data any) *MockAuditLogsModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuditLogsModel)(nil).Update), ctx, data)
	return &MockAuditLogsModelUpdateCall{Call: call}
}

// MockAuditLogsModelUpdateCall wrap *gomock.Call
type MockAuditLogsModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuditLogsModelUpdateCall) Return(arg0 error) *MockAuditLogsModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuditLogsModelUpdateCall) Do(f func(context.Context, *AuditLogs) error) *MockAuditLogsModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuditLogsModelUpdateCall) DoAndReturn(f func(context.Context, *AuditLogs) error) *MockAuditLogsModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockAuditLogsModel) withSession(session sqlx.Session) AuditLogsModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(AuditLogsModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockAuditLogsModelMockRecorder) withSession(session any) *MockAuditLogsModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockAuditLogsModel)(nil).withSession), session)
	return &MockAuditLogsModelwithSessionCall{Call: call}
}

// MockAuditLogsModelwithSessionCall wrap *gomock.Call
type MockAuditLogsModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAuditLogsModelwithSessionCall) Return(arg0 AuditLogsModel) *MockAuditLogsModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAuditLogsModelwithSessionCall) Do(f func(sqlx.Session) AuditLogsModel) *MockAuditLogsModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAuditLogsModelwithSessionCall) DoAndReturn(f func(sqlx.Session) AuditLogsModel) *MockAuditLogsModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
