// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/clienteventsmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/clienteventsmodel.go -destination=db/models/clienteventsmodel_mock.go -package=models -aux_files=models=db/models/clienteventsmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockClientEventsModel is a mock of ClientEventsModel interface.
type MockClientEventsModel struct {
	ctrl     *gomock.Controller
	recorder *MockClientEventsModelMockRecorder
	isgomock struct{}
}

// MockClientEventsModelMockRecorder is the mock recorder for MockClientEventsModel.
type MockClientEventsModelMockRecorder struct {
	mock *MockClientEventsModel
}

// NewMockClientEventsModel creates a new mock instance.
func NewMockClientEventsModel(ctrl *gomock.Controller) *MockClientEventsModel {
	mock := &MockClientEventsModel{ctrl: ctrl}
	mock.recorder = &MockClientEventsModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientEventsModel) EXPECT() *MockClientEventsModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockClientEventsModel) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockClientEventsModelMockRecorder) Delete(ctx, id any) *MockClientEventsModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockClientEventsModel)(nil).Delete), ctx, id)
	return &MockClientEventsModelDeleteCall{Call: call}
}

// MockClientEventsModelDeleteCall wrap *gomock.Call
type MockClientEventsModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientEventsModelDeleteCall) Return(arg0 error) *MockClientEventsModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientEventsModelDeleteCall) Do(f func(context.Context, int64) error) *MockClientEventsModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientEventsModelDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockClientEventsModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockClientEventsModel) FindOne(ctx context.Context, id int64) (*ClientEvents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*ClientEvents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockClientEventsModelMockRecorder) FindOne(ctx, id any) *MockClientEventsModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockClientEventsModel)(nil).FindOne), ctx, id)
	return &MockClientEventsModelFindOneCall{Call: call}
}

// MockClientEventsModelFindOneCall wrap *gomock.Call
type MockClientEventsModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientEventsModelFindOneCall) Return(arg0 *ClientEvents, arg1 error) *MockClientEventsModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientEventsModelFindOneCall) Do(f func(context.Context, int64) (*ClientEvents, error)) *MockClientEventsModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientEventsModelFindOneCall) DoAndReturn(f func(context.Context, int64) (*ClientEvents, error)) *MockClientEventsModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByAppIdEventId mocks base method.
func (m *MockClientEventsModel) FindOneByAppIdEventId(ctx context.Context, appId, eventId string) (*ClientEvents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByAppIdEventId", ctx, appId, eventId)
	ret0, _ := ret[0].(*ClientEvents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByAppIdEventId indicates an expected call of FindOneByAppIdEventId.
func (mr *MockClientEventsModelMockRecorder) FindOneByAppIdEventId(ctx, appId, eventId any) *MockClientEventsModelFindOneByAppIdEventIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByAppIdEventId", reflect.TypeOf((*MockClientEventsModel)(nil).FindOneByAppIdEventId), ctx, appId, eventId)
	return &MockClientEventsModelFindOneByAppIdEventIdCall{Call: call}
}

// MockClientEventsModelFindOneByAppIdEventIdCall wrap *gomock.Call
type MockClientEventsModelFindOneByAppIdEventIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientEventsModelFindOneByAppIdEventIdCall) Return(arg0 *ClientEvents, arg1 error) *MockClientEventsModelFindOneByAppIdEventIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientEventsModelFindOneByAppIdEventIdCall) Do(f func(context.Context, string, string) (*ClientEvents, error)) *MockClientEventsModelFindOneByAppIdEventIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientEventsModelFindOneByAppIdEventIdCall) DoAndReturn(f func(context.Context, string, string) (*ClientEvents, error)) *MockClientEventsModelFindOneByAppIdEventIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockClientEventsModel) Insert(ctx context.Context, data *ClientEvents) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockClientEventsModelMockRecorder) Insert(ctx, data any) *MockClientEventsModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockClientEventsModel)(nil).Insert), ctx, data)
	return &MockClientEventsModelInsertCall{Call: call}
}

// MockClientEventsModelInsertCall wrap *gomock.Call
type MockClientEventsModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientEventsModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockClientEventsModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientEventsModelInsertCall) Do(f func(context.Context, *ClientEvents) (sql.Result, error)) *MockClientEventsModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientEventsModelInsertCall) DoAndReturn(f func(context.Context, *ClientEvents) (sql.Result, error)) *MockClientEventsModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InsertIgnoreConflict mocks base method.
func (m *MockClientEventsModel) InsertIgnoreConflict(ctx context.Context, data *ClientEvents) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertIgnoreConflict", ctx, data)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InsertIgnoreConflict indicates an expected call of InsertIgnoreConflict.
func (mr *MockClientEventsModelMockRecorder) InsertIgnoreConflict(ctx, data any) *MockClientEventsModelInsertIgnoreConflictCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertIgnoreConflict", reflect.TypeOf((*MockClientEventsModel)(nil).InsertIgnoreConflict), ctx, data)
	return &MockClientEventsModelInsertIgnoreConflictCall{Call: call}
}

// MockClientEventsModelInsertIgnoreConflictCall wrap *gomock.Call
type MockClientEventsModelInsertIgnoreConflictCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientEventsModelInsertIgnoreConflictCall) Return(inserted bool, err error) *MockClientEventsModelInsertIgnoreConflictCall {
	c.Call = c.Call.Return(inserted, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientEventsModelInsertIgnoreConflictCall) Do(f func(context.Context, *ClientEvents) (bool, error)) *MockClientEventsModelInsertIgnoreConflictCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientEventsModelInsertIgnoreConflictCall) DoAndReturn(f func(context.Context, *ClientEvents) (bool, error)) *MockClientEventsModelInsertIgnoreConflictCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// StatsByUpdate mocks base method.
func (m *MockClientEventsModel) StatsByUpdate(ctx context.Context, appId, updateId string) (*ClientEventUpdateStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatsByUpdate", ctx, appId, updateId)
	ret0, _ := ret[0].(*ClientEventUpdateStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// StatsByUpdate indicates an expected call of StatsByUpdate.
func (mr *MockClientEventsModelMockRecorder) StatsByUpdate(ctx, appId, updateId any) *MockClientEventsModelStatsByUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatsByUpdate", reflect.TypeOf((*MockClientEventsModel)(nil).StatsByUpdate), ctx, appId, updateId)
	return &MockClientEventsModelStatsByUpdateCall{Call: call}
}

// MockClientEventsModelStatsByUpdateCall wrap *gomock.Call
type MockClientEventsModelStatsByUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientEventsModelStatsByUpdateCall) Return(arg0 *ClientEventUpdateStats, arg1 error) *MockClientEventsModelStatsByUpdateCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientEventsModelStatsByUpdateCall) Do(f func(context.Context, string, string) (*ClientEventUpdateStats, error)) *MockClientEventsModelStatsByUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientEventsModelStatsByUpdateCall) DoAndReturn(f func(context.Context, string, string) (*ClientEventUpdateStats, error)) *MockClientEventsModelStatsByUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockClientEventsModel) Update(ctx context.Context, data *ClientEvents) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockClientEventsModelMockRecorder) Update(ctx, data any) *MockClientEventsModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockClientEventsModel)(nil).Update), ctx, data)
	return &MockClientEventsModelUpdateCall{Call: call}
}

// MockClientEventsModelUpdateCall wrap *gomock.Call
type MockClientEventsModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientEventsModelUpdateCall) Return(arg0 error) *MockClientEventsModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientEventsModelUpdateCall) Do(f func(context.Context, *ClientEvents) error) *MockClientEventsModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientEventsModelUpdateCall) DoAndReturn(f func(context.Context, *ClientEvents) error) *MockClientEventsModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockClientEventsModel) withSession(session sqlx.Session) ClientEventsModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(ClientEventsModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockClientEventsModelMockRecorder) withSession(session any) *MockClientEventsModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockClientEventsModel)(nil).withSession), session)
	return &MockClientEventsModelwithSessionCall{Call: call}
}

// MockClientEventsModelwithSessionCall wrap *gomock.Call
type MockClientEventsModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClientEventsModelwithSessionCall) Return(arg0 ClientEventsModel) *MockClientEventsModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClientEventsModelwithSessionCall) Do(f func(sqlx.Session) ClientEventsModel) *MockClientEventsModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClientEventsModelwithSessionCall) DoAndReturn(f func(sqlx.Session) ClientEventsModel) *MockClientEventsModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
