// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	clientEventsFieldNames          = builder.RawFieldNames(&ClientEvents{}, true)
	clientEventsRows                = strings.Join(clientEventsFieldNames, ",")
	clientEventsRowsExpectAutoSet   = strings.Join(stringx.Remove(clientEventsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	clientEventsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(clientEventsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	clientEventsModel interface {
		Insert(ctx context.Context, data *ClientEvents) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ClientEvents, error)
		FindOneByAppIdEventId(ctx context.Context, appId string, eventId string) (*ClientEvents, error)
		Update(ctx context.Context, data *ClientEvents) error
		Delete(ctx context.Context, id int64) error
	}

	defaultClientEventsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ClientEvents struct {
		Id             int64          `db:"id"`
		AppId          string         `db:"app_id"`
		OccurredAt     time.Time      `db:"occurred_at"`
		ReceivedAt     time.Time      `db:"received_at"`
		EventId        string         `db:"event_id"`
		EventType      string         `db:"event_type"`
		UpdateId       sql.NullString `db:"update_id"`
		ManifestUuid   sql.NullString `db:"manifest_uuid"`
		RuntimeVersion sql.NullString `db:"runtime_version"`
		Platform       sql.NullString `db:"platform"`
		DeviceId       string         `db:"device_id"`
		AppVersion     sql.NullString `db:"app_version"`
		OsVersion      sql.NullString `db:"os_version"`
		DurationMs     sql.NullInt64  `db:"duration_ms"`
		ErrorCode      sql.NullString `db:"error_code"`
		ErrorMessage   sql.NullString `db:"error_message"`
	}
)

func newClientEventsModel(conn sqlx.SqlConn) *defaultClientEventsModel {
	return &defaultClientEventsModel{
		conn:  conn,
		table: `"public"."client_events"`,
	}
}

func (m *defaultClientEventsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultClientEventsModel) FindOne(ctx context.Context, id int64) (*ClientEvents, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", clientEventsRows, m.table)
	var resp ClientEvents
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientEventsModel) FindOneByAppIdEventId(ctx context.Context, appId string, eventId string) (*ClientEvents, error) {
	var resp ClientEvents
	query := fmt.Sprintf("select %s from %s where app_id = $1 and event_id = $2 limit 1", clientEventsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, appId, eventId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultClientEventsModel) Insert(ctx context.Context, data *ClientEvents) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)", m.table, clientEventsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AppId, data.OccurredAt, data.ReceivedAt, data.EventId, data.EventType, data.UpdateId, data.ManifestUuid, data.RuntimeVersion, data.Platform, data.DeviceId, data.AppVersion, data.OsVersion, data.DurationMs, data.ErrorCode, data.ErrorMessage)
	return ret, err
}

func (m *defaultClientEventsModel) Update(ctx context.Context, newData *ClientEvents) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, clientEventsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.AppId, newData.OccurredAt, newData.ReceivedAt, newData.EventId, newData.EventType, newData.UpdateId, newData.ManifestUuid, newData.RuntimeVersion, newData.Platform, newData.DeviceId, newData.AppVersion, newData.OsVersion, newData.DurationMs, newData.ErrorCode, newData.ErrorMessage)
	return err
}

func (m *defaultClientEventsModel) tableName() string {
	return m.table
}
