// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	codeSigningKeysFieldNames          = builder.RawFieldNames(&CodeSigningKeys{}, true)
	codeSigningKeysRows                = strings.Join(codeSigningKeysFieldNames, ",")
	codeSigningKeysRowsExpectAutoSet   = strings.Join(stringx.Remove(codeSigningKeysFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	codeSigningKeysRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(codeSigningKeysFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	codeSigningKeysModel interface {
		Insert(ctx context.Context, data *CodeSigningKeys) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*CodeSigningKeys, error)
		FindOneByAppIdKeyId(ctx context.Context, appId string, keyId string) (*CodeSigningKeys, error)
		Update(ctx context.Context, data *CodeSigningKeys) error
		Delete(ctx context.Context, id string) error
	}

	defaultCodeSigningKeysModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CodeSigningKeys struct {
		Id                  string       `db:"id"`
		AppId               string       `db:"app_id"`
		KeyId               string       `db:"key_id"`
		Algorithm           string       `db:"algorithm"`
		PublicKeyPem        string       `db:"public_key_pem"`
		EncryptedPrivateKey string       `db:"encrypted_private_key"`
		EncryptionKeyId     string       `db:"encryption_key_id"`
		Enabled             bool         `db:"enabled"`
		CreatedAt           time.Time    `db:"created_at"`
		DisabledAt          sql.NullTime `db:"disabled_at"`
	}
)

func newCodeSigningKeysModel(conn sqlx.SqlConn) *defaultCodeSigningKeysModel {
	return &defaultCodeSigningKeysModel{
		conn:  conn,
		table: `"public"."code_signing_keys"`,
	}
}

func (m *defaultCodeSigningKeysModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCodeSigningKeysModel) FindOne(ctx context.Context, id string) (*CodeSigningKeys, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", codeSigningKeysRows, m.table)
	var resp CodeSigningKeys
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCodeSigningKeysModel) FindOneByAppIdKeyId(ctx context.Context, appId string, keyId string) (*CodeSigningKeys, error) {
	var resp CodeSigningKeys
	query := fmt.Sprintf("select %s from %s where app_id = $1 and key_id = $2 limit 1", codeSigningKeysRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, appId, keyId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCodeSigningKeysModel) Insert(ctx context.Context, data *CodeSigningKeys) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)", m.table, codeSigningKeysRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.AppId, data.KeyId, data.Algorithm, data.PublicKeyPem, data.EncryptedPrivateKey, data.EncryptionKeyId, data.Enabled, data.DisabledAt)
	return ret, err
}

func (m *defaultCodeSigningKeysModel) Update(ctx context.Context, newData *CodeSigningKeys) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, codeSigningKeysRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.AppId, newData.KeyId, newData.Algorithm, newData.PublicKeyPem, newData.EncryptedPrivateKey, newData.EncryptionKeyId, newData.Enabled, newData.DisabledAt)
	return err
}

func (m *defaultCodeSigningKeysModel) tableName() string {
	return m.table
}
