// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/codesigningkeysmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/codesigningkeysmodel.go -destination=db/models/codesigningkeysmodel_mock.go -package=models -aux_files=models=db/models/codesigningkeysmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockCodeSigningKeysModel is a mock of CodeSigningKeysModel interface.
type MockCodeSigningKeysModel struct {
	ctrl     *gomock.Controller
	recorder *MockCodeSigningKeysModelMockRecorder
	isgomock struct{}
}

// MockCodeSigningKeysModelMockRecorder is the mock recorder for MockCodeSigningKeysModel.
type MockCodeSigningKeysModelMockRecorder struct {
	mock *MockCodeSigningKeysModel
}

// NewMockCodeSigningKeysModel creates a new mock instance.
func NewMockCodeSigningKeysModel(ctrl *gomock.Controller) *MockCodeSigningKeysModel {
	mock := &MockCodeSigningKeysModel{ctrl: ctrl}
	mock.recorder = &MockCodeSigningKeysModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCodeSigningKeysModel) EXPECT() *MockCodeSigningKeysModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCodeSigningKeysModel) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCodeSigningKeysModelMockRecorder) Delete(ctx, id any) *MockCodeSigningKeysModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCodeSigningKeysModel)(nil).Delete), ctx, id)
	return &MockCodeSigningKeysModelDeleteCall{Call: call}
}

// MockCodeSigningKeysModelDeleteCall wrap *gomock.Call
type MockCodeSigningKeysModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeSigningKeysModelDeleteCall) Return(arg0 error) *MockCodeSigningKeysModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeSigningKeysModelDeleteCall) Do(f func(context.Context, string) error) *MockCodeSigningKeysModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeSigningKeysModelDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockCodeSigningKeysModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockCodeSigningKeysModel) FindOne(ctx context.Context, id string) (*CodeSigningKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*CodeSigningKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockCodeSigningKeysModelMockRecorder) FindOne(ctx, id any) *MockCodeSigningKeysModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockCodeSigningKeysModel)(nil).FindOne), ctx, id)
	return &MockCodeSigningKeysModelFindOneCall{Call: call}
}

// MockCodeSigningKeysModelFindOneCall wrap *gomock.Call
type MockCodeSigningKeysModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeSigningKeysModelFindOneCall) Return(arg0 *CodeSigningKeys, arg1 error) *MockCodeSigningKeysModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeSigningKeysModelFindOneCall) Do(f func(context.Context, string) (*CodeSigningKeys, error)) *MockCodeSigningKeysModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeSigningKeysModelFindOneCall) DoAndReturn(f func(context.Context, string) (*CodeSigningKeys, error)) *MockCodeSigningKeysModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByAppId mocks base method.
func (m *MockCodeSigningKeysModel) FindOneByAppId(ctx context.Context, appId string) (*CodeSigningKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByAppId", ctx, appId)
	ret0, _ := ret[0].(*CodeSigningKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByAppId indicates an expected call of FindOneByAppId.
func (mr *MockCodeSigningKeysModelMockRecorder) FindOneByAppId(ctx, appId any) *MockCodeSigningKeysModelFindOneByAppIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByAppId", reflect.TypeOf((*MockCodeSigningKeysModel)(nil).FindOneByAppId), ctx, appId)
	return &MockCodeSigningKeysModelFindOneByAppIdCall{Call: call}
}

// MockCodeSigningKeysModelFindOneByAppIdCall wrap *gomock.Call
type MockCodeSigningKeysModelFindOneByAppIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeSigningKeysModelFindOneByAppIdCall) Return(arg0 *CodeSigningKeys, arg1 error) *MockCodeSigningKeysModelFindOneByAppIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeSigningKeysModelFindOneByAppIdCall) Do(f func(context.Context, string) (*CodeSigningKeys, error)) *MockCodeSigningKeysModelFindOneByAppIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeSigningKeysModelFindOneByAppIdCall) DoAndReturn(f func(context.Context, string) (*CodeSigningKeys, error)) *MockCodeSigningKeysModelFindOneByAppIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByAppIdKeyId mocks base method.
func (m *MockCodeSigningKeysModel) FindOneByAppIdKeyId(ctx context.Context, appId, keyId string) (*CodeSigningKeys, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByAppIdKeyId", ctx, appId, keyId)
	ret0, _ := ret[0].(*CodeSigningKeys)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByAppIdKeyId indicates an expected call of FindOneByAppIdKeyId.
func (mr *MockCodeSigningKeysModelMockRecorder) FindOneByAppIdKeyId(ctx, appId, keyId any) *MockCodeSigningKeysModelFindOneByAppIdKeyIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByAppIdKeyId", reflect.TypeOf((*MockCodeSigningKeysModel)(nil).FindOneByAppIdKeyId), ctx, appId, keyId)
	return &MockCodeSigningKeysModelFindOneByAppIdKeyIdCall{Call: call}
}

// MockCodeSigningKeysModelFindOneByAppIdKeyIdCall wrap *gomock.Call
type MockCodeSigningKeysModelFindOneByAppIdKeyIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeSigningKeysModelFindOneByAppIdKeyIdCall) Return(arg0 *CodeSigningKeys, arg1 error) *MockCodeSigningKeysModelFindOneByAppIdKeyIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeSigningKeysModelFindOneByAppIdKeyIdCall) Do(f func(context.Context, string, string) (*CodeSigningKeys, error)) *MockCodeSigningKeysModelFindOneByAppIdKeyIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeSigningKeysModelFindOneByAppIdKeyIdCall) DoAndReturn(f func(context.Context, string, string) (*CodeSigningKeys, error)) *MockCodeSigningKeysModelFindOneByAppIdKeyIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockCodeSigningKeysModel) Insert(ctx context.Context, data *CodeSigningKeys) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockCodeSigningKeysModelMockRecorder) Insert(ctx, data any) *MockCodeSigningKeysModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockCodeSigningKeysModel)(nil).Insert), ctx, data)
	return &MockCodeSigningKeysModelInsertCall{Call: call}
}

// MockCodeSigningKeysModelInsertCall wrap *gomock.Call
type MockCodeSigningKeysModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeSigningKeysModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockCodeSigningKeysModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeSigningKeysModelInsertCall) Do(f func(context.Context, *CodeSigningKeys) (sql.Result, error)) *MockCodeSigningKeysModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeSigningKeysModelInsertCall) DoAndReturn(f func(context.Context, *CodeSigningKeys) (sql.Result, error)) *MockCodeSigningKeysModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockCodeSigningKeysModel) Update(ctx context.Context, data *CodeSigningKeys) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockCodeSigningKeysModelMockRecorder) Update(ctx, data any) *MockCodeSigningKeysModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCodeSigningKeysModel)(nil).Update), ctx, data)
	return &MockCodeSigningKeysModelUpdateCall{Call: call}
}

// MockCodeSigningKeysModelUpdateCall wrap *gomock.Call
type MockCodeSigningKeysModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeSigningKeysModelUpdateCall) Return(arg0 error) *MockCodeSigningKeysModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeSigningKeysModelUpdateCall) Do(f func(context.Context, *CodeSigningKeys) error) *MockCodeSigningKeysModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeSigningKeysModelUpdateCall) DoAndReturn(f func(context.Context, *CodeSigningKeys) error) *MockCodeSigningKeysModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockCodeSigningKeysModel) withSession(session sqlx.Session) CodeSigningKeysModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(CodeSigningKeysModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockCodeSigningKeysModelMockRecorder) withSession(session any) *MockCodeSigningKeysModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockCodeSigningKeysModel)(nil).withSession), session)
	return &MockCodeSigningKeysModelwithSessionCall{Call: call}
}

// MockCodeSigningKeysModelwithSessionCall wrap *gomock.Call
type MockCodeSigningKeysModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCodeSigningKeysModelwithSessionCall) Return(arg0 CodeSigningKeysModel) *MockCodeSigningKeysModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCodeSigningKeysModelwithSessionCall) Do(f func(sqlx.Session) CodeSigningKeysModel) *MockCodeSigningKeysModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCodeSigningKeysModelwithSessionCall) DoAndReturn(f func(sqlx.Session) CodeSigningKeysModel) *MockCodeSigningKeysModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
