// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/manifestrequestsmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/manifestrequestsmodel.go -destination=db/models/manifestrequestsmodel_mock.go -package=models -aux_files=models=db/models/manifestrequestsmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockManifestRequestsModel is a mock of ManifestRequestsModel interface.
type MockManifestRequestsModel struct {
	ctrl     *gomock.Controller
	recorder *MockManifestRequestsModelMockRecorder
	isgomock struct{}
}

// MockManifestRequestsModelMockRecorder is the mock recorder for MockManifestRequestsModel.
type MockManifestRequestsModelMockRecorder struct {
	mock *MockManifestRequestsModel
}

// NewMockManifestRequestsModel creates a new mock instance.
func NewMockManifestRequestsModel(ctrl *gomock.Controller) *MockManifestRequestsModel {
	mock := &MockManifestRequestsModel{ctrl: ctrl}
	mock.recorder = &MockManifestRequestsModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockManifestRequestsModel) EXPECT() *MockManifestRequestsModelMockRecorder {
	return m.recorder
}

// CountDistinctDevices mocks base method.
func (m *MockManifestRequestsModel) CountDistinctDevices(ctx context.Context, appId, servedUpdateId string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountDistinctDevices", ctx, appId, servedUpdateId)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountDistinctDevices indicates an expected call of CountDistinctDevices.
func (mr *MockManifestRequestsModelMockRecorder) CountDistinctDevices(ctx, appId, servedUpdateId any) *MockManifestRequestsModelCountDistinctDevicesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountDistinctDevices", reflect.TypeOf((*MockManifestRequestsModel)(nil).CountDistinctDevices), ctx, appId, servedUpdateId)
	return &MockManifestRequestsModelCountDistinctDevicesCall{Call: call}
}

// MockManifestRequestsModelCountDistinctDevicesCall wrap *gomock.Call
type MockManifestRequestsModelCountDistinctDevicesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestRequestsModelCountDistinctDevicesCall) Return(arg0 int64, arg1 error) *MockManifestRequestsModelCountDistinctDevicesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestRequestsModelCountDistinctDevicesCall) Do(f func(context.Context, string, string) (int64, error)) *MockManifestRequestsModelCountDistinctDevicesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestRequestsModelCountDistinctDevicesCall) DoAndReturn(f func(context.Context, string, string) (int64, error)) *MockManifestRequestsModelCountDistinctDevicesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockManifestRequestsModel) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockManifestRequestsModelMockRecorder) Delete(ctx, id any) *MockManifestRequestsModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockManifestRequestsModel)(nil).Delete), ctx, id)
	return &MockManifestRequestsModelDeleteCall{Call: call}
}

// MockManifestRequestsModelDeleteCall wrap *gomock.Call
type MockManifestRequestsModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestRequestsModelDeleteCall) Return(arg0 error) *MockManifestRequestsModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestRequestsModelDeleteCall) Do(f func(context.Context, int64) error) *MockManifestRequestsModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestRequestsModelDeleteCall) DoAndReturn(f func(context.Context, int64) error) *MockManifestRequestsModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockManifestRequestsModel) FindOne(ctx context.Context, id int64) (*ManifestRequests, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*ManifestRequests)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockManifestRequestsModelMockRecorder) FindOne(ctx, id any) *MockManifestRequestsModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockManifestRequestsModel)(nil).FindOne), ctx, id)
	return &MockManifestRequestsModelFindOneCall{Call: call}
}

// MockManifestRequestsModelFindOneCall wrap *gomock.Call
type MockManifestRequestsModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestRequestsModelFindOneCall) Return(arg0 *ManifestRequests, arg1 error) *MockManifestRequestsModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestRequestsModelFindOneCall) Do(f func(context.Context, int64) (*ManifestRequests, error)) *MockManifestRequestsModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestRequestsModelFindOneCall) DoAndReturn(f func(context.Context, int64) (*ManifestRequests, error)) *MockManifestRequestsModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockManifestRequestsModel) Insert(ctx context.Context, data *ManifestRequests) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockManifestRequestsModelMockRecorder) Insert(ctx, data any) *MockManifestRequestsModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockManifestRequestsModel)(nil).Insert), ctx, data)
	return &MockManifestRequestsModelInsertCall{Call: call}
}

// MockManifestRequestsModelInsertCall wrap *gomock.Call
type MockManifestRequestsModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestRequestsModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockManifestRequestsModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestRequestsModelInsertCall) Do(f func(context.Context, *ManifestRequests) (sql.Result, error)) *MockManifestRequestsModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestRequestsModelInsertCall) DoAndReturn(f func(context.Context, *ManifestRequests) (sql.Result, error)) *MockManifestRequestsModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockManifestRequestsModel) Update(ctx context.Context, data *ManifestRequests) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockManifestRequestsModelMockRecorder) Update(ctx, data any) *MockManifestRequestsModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockManifestRequestsModel)(nil).Update), ctx, data)
	return &MockManifestRequestsModelUpdateCall{Call: call}
}

// MockManifestRequestsModelUpdateCall wrap *gomock.Call
type MockManifestRequestsModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestRequestsModelUpdateCall) Return(arg0 error) *MockManifestRequestsModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestRequestsModelUpdateCall) Do(f func(context.Context, *ManifestRequests) error) *MockManifestRequestsModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestRequestsModelUpdateCall) DoAndReturn(f func(context.Context, *ManifestRequests) error) *MockManifestRequestsModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockManifestRequestsModel) withSession(session sqlx.Session) ManifestRequestsModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(ManifestRequestsModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockManifestRequestsModelMockRecorder) withSession(session any) *MockManifestRequestsModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockManifestRequestsModel)(nil).withSession), session)
	return &MockManifestRequestsModelwithSessionCall{Call: call}
}

// MockManifestRequestsModelwithSessionCall wrap *gomock.Call
type MockManifestRequestsModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockManifestRequestsModelwithSessionCall) Return(arg0 ManifestRequestsModel) *MockManifestRequestsModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockManifestRequestsModelwithSessionCall) Do(f func(sqlx.Session) ManifestRequestsModel) *MockManifestRequestsModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockManifestRequestsModelwithSessionCall) DoAndReturn(f func(sqlx.Session) ManifestRequestsModel) *MockManifestRequestsModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
