// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	manifestRequestsFieldNames          = builder.RawFieldNames(&ManifestRequests{}, true)
	manifestRequestsRows                = strings.Join(manifestRequestsFieldNames, ",")
	manifestRequestsRowsExpectAutoSet   = strings.Join(stringx.Remove(manifestRequestsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	manifestRequestsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(manifestRequestsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	manifestRequestsModel interface {
		Insert(ctx context.Context, data *ManifestRequests) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*ManifestRequests, error)
		Update(ctx context.Context, data *ManifestRequests) error
		Delete(ctx context.Context, id int64) error
	}

	defaultManifestRequestsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	ManifestRequests struct {
		Id             int64          `db:"id"`
		AppId          string         `db:"app_id"`
		OccurredAt     time.Time      `db:"occurred_at"`
		RuntimeVersion string         `db:"runtime_version"`
		Platform       string         `db:"platform"`
		DeviceId       sql.NullString `db:"device_id"`
		ServedUpdateId sql.NullString `db:"served_update_id"`
		Result         string         `db:"result"`
		HttpStatus     int64          `db:"http_status"`
	}
)

func newManifestRequestsModel(conn sqlx.SqlConn) *defaultManifestRequestsModel {
	return &defaultManifestRequestsModel{
		conn:  conn,
		table: `"public"."manifest_requests"`,
	}
}

func (m *defaultManifestRequestsModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultManifestRequestsModel) FindOne(ctx context.Context, id int64) (*ManifestRequests, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", manifestRequestsRows, m.table)
	var resp ManifestRequests
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultManifestRequestsModel) Insert(ctx context.Context, data *ManifestRequests) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8)", m.table, manifestRequestsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.AppId, data.OccurredAt, data.RuntimeVersion, data.Platform, data.DeviceId, data.ServedUpdateId, data.Result, data.HttpStatus)
	return ret, err
}

func (m *defaultManifestRequestsModel) Update(ctx context.Context, data *ManifestRequests) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, manifestRequestsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Id, data.AppId, data.OccurredAt, data.RuntimeVersion, data.Platform, data.DeviceId, data.ServedUpdateId, data.Result, data.HttpStatus)
	return err
}

func (m *defaultManifestRequestsModel) tableName() string {
	return m.table
}
