// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	runtimeVersionsFieldNames          = builder.RawFieldNames(&RuntimeVersions{}, true)
	runtimeVersionsRows                = strings.Join(runtimeVersionsFieldNames, ",")
	runtimeVersionsRowsExpectAutoSet   = strings.Join(stringx.Remove(runtimeVersionsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	runtimeVersionsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(runtimeVersionsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	runtimeVersionsModel interface {
		Insert(ctx context.Context, data *RuntimeVersions) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*RuntimeVersions, error)
		FindOneByAppIdVersion(ctx context.Context, appId string, version string) (*RuntimeVersions, error)
		Update(ctx context.Context, data *RuntimeVersions) error
		Delete(ctx context.Context, id string) error
	}

	defaultRuntimeVersionsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	RuntimeVersions struct {
		Id        string    `db:"id"`
		AppId     string    `db:"app_id"`
		Version   string    `db:"version"`
		CreatedAt time.Time `db:"created_at"`
	}
)

func newRuntimeVersionsModel(conn sqlx.SqlConn) *defaultRuntimeVersionsModel {
	return &defaultRuntimeVersionsModel{
		conn:  conn,
		table: `"public"."runtime_versions"`,
	}
}

func (m *defaultRuntimeVersionsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultRuntimeVersionsModel) FindOne(ctx context.Context, id string) (*RuntimeVersions, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", runtimeVersionsRows, m.table)
	var resp RuntimeVersions
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRuntimeVersionsModel) FindOneByAppIdVersion(ctx context.Context, appId string, version string) (*RuntimeVersions, error) {
	var resp RuntimeVersions
	query := fmt.Sprintf("select %s from %s where app_id = $1 and version = $2 limit 1", runtimeVersionsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, appId, version)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRuntimeVersionsModel) Insert(ctx context.Context, data *RuntimeVersions) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3)", m.table, runtimeVersionsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.AppId, data.Version)
	return ret, err
}

func (m *defaultRuntimeVersionsModel) Update(ctx context.Context, newData *RuntimeVersions) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, runtimeVersionsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.AppId, newData.Version)
	return err
}

func (m *defaultRuntimeVersionsModel) tableName() string {
	return m.table
}
