// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/runtimeversionsmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/runtimeversionsmodel.go -destination=db/models/runtimeversionsmodel_mock.go -package=models -aux_files=models=db/models/runtimeversionsmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockRuntimeVersionsModel is a mock of RuntimeVersionsModel interface.
type MockRuntimeVersionsModel struct {
	ctrl     *gomock.Controller
	recorder *MockRuntimeVersionsModelMockRecorder
	isgomock struct{}
}

// MockRuntimeVersionsModelMockRecorder is the mock recorder for MockRuntimeVersionsModel.
type MockRuntimeVersionsModelMockRecorder struct {
	mock *MockRuntimeVersionsModel
}

// NewMockRuntimeVersionsModel creates a new mock instance.
func NewMockRuntimeVersionsModel(ctrl *gomock.Controller) *MockRuntimeVersionsModel {
	mock := &MockRuntimeVersionsModel{ctrl: ctrl}
	mock.recorder = &MockRuntimeVersionsModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRuntimeVersionsModel) EXPECT() *MockRuntimeVersionsModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockRuntimeVersionsModel) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRuntimeVersionsModelMockRecorder) Delete(ctx, id any) *MockRuntimeVersionsModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRuntimeVersionsModel)(nil).Delete), ctx, id)
	return &MockRuntimeVersionsModelDeleteCall{Call: call}
}

// MockRuntimeVersionsModelDeleteCall wrap *gomock.Call
type MockRuntimeVersionsModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRuntimeVersionsModelDeleteCall) Return(arg0 error) *MockRuntimeVersionsModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRuntimeVersionsModelDeleteCall) Do(f func(context.Context, string) error) *MockRuntimeVersionsModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRuntimeVersionsModelDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockRuntimeVersionsModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockRuntimeVersionsModel) FindOne(ctx context.Context, id string) (*RuntimeVersions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*RuntimeVersions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockRuntimeVersionsModelMockRecorder) FindOne(ctx, id any) *MockRuntimeVersionsModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockRuntimeVersionsModel)(nil).FindOne), ctx, id)
	return &MockRuntimeVersionsModelFindOneCall{Call: call}
}

// MockRuntimeVersionsModelFindOneCall wrap *gomock.Call
type MockRuntimeVersionsModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRuntimeVersionsModelFindOneCall) Return(arg0 *RuntimeVersions, arg1 error) *MockRuntimeVersionsModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRuntimeVersionsModelFindOneCall) Do(f func(context.Context, string) (*RuntimeVersions, error)) *MockRuntimeVersionsModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRuntimeVersionsModelFindOneCall) DoAndReturn(f func(context.Context, string) (*RuntimeVersions, error)) *MockRuntimeVersionsModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByAppIdVersion mocks base method.
func (m *MockRuntimeVersionsModel) FindOneByAppIdVersion(ctx context.Context, appId, version string) (*RuntimeVersions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByAppIdVersion", ctx, appId, version)
	ret0, _ := ret[0].(*RuntimeVersions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByAppIdVersion indicates an expected call of FindOneByAppIdVersion.
func (mr *MockRuntimeVersionsModelMockRecorder) FindOneByAppIdVersion(ctx, appId, version any) *MockRuntimeVersionsModelFindOneByAppIdVersionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByAppIdVersion", reflect.TypeOf((*MockRuntimeVersionsModel)(nil).FindOneByAppIdVersion), ctx, appId, version)
	return &MockRuntimeVersionsModelFindOneByAppIdVersionCall{Call: call}
}

// MockRuntimeVersionsModelFindOneByAppIdVersionCall wrap *gomock.Call
type MockRuntimeVersionsModelFindOneByAppIdVersionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRuntimeVersionsModelFindOneByAppIdVersionCall) Return(arg0 *RuntimeVersions, arg1 error) *MockRuntimeVersionsModelFindOneByAppIdVersionCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRuntimeVersionsModelFindOneByAppIdVersionCall) Do(f func(context.Context, string, string) (*RuntimeVersions, error)) *MockRuntimeVersionsModelFindOneByAppIdVersionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRuntimeVersionsModelFindOneByAppIdVersionCall) DoAndReturn(f func(context.Context, string, string) (*RuntimeVersions, error)) *MockRuntimeVersionsModelFindOneByAppIdVersionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockRuntimeVersionsModel) Insert(ctx context.Context, data *RuntimeVersions) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockRuntimeVersionsModelMockRecorder) Insert(ctx, data any) *MockRuntimeVersionsModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockRuntimeVersionsModel)(nil).Insert), ctx, data)
	return &MockRuntimeVersionsModelInsertCall{Call: call}
}

// MockRuntimeVersionsModelInsertCall wrap *gomock.Call
type MockRuntimeVersionsModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRuntimeVersionsModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockRuntimeVersionsModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRuntimeVersionsModelInsertCall) Do(f func(context.Context, *RuntimeVersions) (sql.Result, error)) *MockRuntimeVersionsModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRuntimeVersionsModelInsertCall) DoAndReturn(f func(context.Context, *RuntimeVersions) (sql.Result, error)) *MockRuntimeVersionsModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockRuntimeVersionsModel) Update(ctx context.Context, data *RuntimeVersions) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockRuntimeVersionsModelMockRecorder) Update(ctx, data any) *MockRuntimeVersionsModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRuntimeVersionsModel)(nil).Update), ctx, data)
	return &MockRuntimeVersionsModelUpdateCall{Call: call}
}

// MockRuntimeVersionsModelUpdateCall wrap *gomock.Call
type MockRuntimeVersionsModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRuntimeVersionsModelUpdateCall) Return(arg0 error) *MockRuntimeVersionsModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRuntimeVersionsModelUpdateCall) Do(f func(context.Context, *RuntimeVersions) error) *MockRuntimeVersionsModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRuntimeVersionsModelUpdateCall) DoAndReturn(f func(context.Context, *RuntimeVersions) error) *MockRuntimeVersionsModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockRuntimeVersionsModel) withSession(session sqlx.Session) RuntimeVersionsModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(RuntimeVersionsModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockRuntimeVersionsModelMockRecorder) withSession(session any) *MockRuntimeVersionsModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockRuntimeVersionsModel)(nil).withSession), session)
	return &MockRuntimeVersionsModelwithSessionCall{Call: call}
}

// MockRuntimeVersionsModelwithSessionCall wrap *gomock.Call
type MockRuntimeVersionsModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRuntimeVersionsModelwithSessionCall) Return(arg0 RuntimeVersionsModel) *MockRuntimeVersionsModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRuntimeVersionsModelwithSessionCall) Do(f func(sqlx.Session) RuntimeVersionsModel) *MockRuntimeVersionsModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRuntimeVersionsModelwithSessionCall) DoAndReturn(f func(sqlx.Session) RuntimeVersionsModel) *MockRuntimeVersionsModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
