// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/updatesmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/updatesmodel.go -destination=db/models/updatesmodel_mock.go -package=models -aux_files=models=db/models/updatesmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdatesModel is a mock of UpdatesModel interface.
type MockUpdatesModel struct {
	ctrl     *gomock.Controller
	recorder *MockUpdatesModelMockRecorder
	isgomock struct{}
}

// MockUpdatesModelMockRecorder is the mock recorder for MockUpdatesModel.
type MockUpdatesModelMockRecorder struct {
	mock *MockUpdatesModel
}

// NewMockUpdatesModel creates a new mock instance.
func NewMockUpdatesModel(ctrl *gomock.Controller) *MockUpdatesModel {
	mock := &MockUpdatesModel{ctrl: ctrl}
	mock.recorder = &MockUpdatesModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdatesModel) EXPECT() *MockUpdatesModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUpdatesModel) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUpdatesModelMockRecorder) Delete(ctx, id any) *MockUpdatesModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUpdatesModel)(nil).Delete), ctx, id)
	return &MockUpdatesModelDeleteCall{Call: call}
}

// MockUpdatesModelDeleteCall wrap *gomock.Call
type MockUpdatesModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelDeleteCall) Return(arg0 error) *MockUpdatesModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelDeleteCall) Do(f func(context.Context, string) error) *MockUpdatesModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockUpdatesModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindLatestPublished mocks base method.
func (m *MockUpdatesModel) FindLatestPublished(ctx context.Context, appId, runtimeVersionId, platform string) (*Updates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestPublished", ctx, appId, runtimeVersionId, platform)
	ret0, _ := ret[0].(*Updates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestPublished indicates an expected call of FindLatestPublished.
func (mr *MockUpdatesModelMockRecorder) FindLatestPublished(ctx, appId, runtimeVersionId, platform any) *MockUpdatesModelFindLatestPublishedCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestPublished", reflect.TypeOf((*MockUpdatesModel)(nil).FindLatestPublished), ctx, appId, runtimeVersionId, platform)
	return &MockUpdatesModelFindLatestPublishedCall{Call: call}
}

// MockUpdatesModelFindLatestPublishedCall wrap *gomock.Call
type MockUpdatesModelFindLatestPublishedCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelFindLatestPublishedCall) Return(arg0 *Updates, arg1 error) *MockUpdatesModelFindLatestPublishedCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelFindLatestPublishedCall) Do(f func(context.Context, string, string, string) (*Updates, error)) *MockUpdatesModelFindLatestPublishedCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelFindLatestPublishedCall) DoAndReturn(f func(context.Context, string, string, string) (*Updates, error)) *MockUpdatesModelFindLatestPublishedCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindManyByAppId mocks base method.
func (m *MockUpdatesModel) FindManyByAppId(ctx context.Context, appId string, filter UpdatesFilter) ([]*Updates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindManyByAppId", ctx, appId, filter)
	ret0, _ := ret[0].([]*Updates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindManyByAppId indicates an expected call of FindManyByAppId.
func (mr *MockUpdatesModelMockRecorder) FindManyByAppId(ctx, appId, filter any) *MockUpdatesModelFindManyByAppIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindManyByAppId", reflect.TypeOf((*MockUpdatesModel)(nil).FindManyByAppId), ctx, appId, filter)
	return &MockUpdatesModelFindManyByAppIdCall{Call: call}
}

// MockUpdatesModelFindManyByAppIdCall wrap *gomock.Call
type MockUpdatesModelFindManyByAppIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelFindManyByAppIdCall) Return(arg0 []*Updates, arg1 error) *MockUpdatesModelFindManyByAppIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelFindManyByAppIdCall) Do(f func(context.Context, string, UpdatesFilter) ([]*Updates, error)) *MockUpdatesModelFindManyByAppIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelFindManyByAppIdCall) DoAndReturn(f func(context.Context, string, UpdatesFilter) ([]*Updates, error)) *MockUpdatesModelFindManyByAppIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockUpdatesModel) FindOne(ctx context.Context, id string) (*Updates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*Updates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockUpdatesModelMockRecorder) FindOne(ctx, id any) *MockUpdatesModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockUpdatesModel)(nil).FindOne), ctx, id)
	return &MockUpdatesModelFindOneCall{Call: call}
}

// MockUpdatesModelFindOneCall wrap *gomock.Call
type MockUpdatesModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelFindOneCall) Return(arg0 *Updates, arg1 error) *MockUpdatesModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelFindOneCall) Do(f func(context.Context, string) (*Updates, error)) *MockUpdatesModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelFindOneCall) DoAndReturn(f func(context.Context, string) (*Updates, error)) *MockUpdatesModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByAppIdManifestUuid mocks base method.
func (m *MockUpdatesModel) FindOneByAppIdManifestUuid(ctx context.Context, appId, manifestUuid string) (*Updates, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByAppIdManifestUuid", ctx, appId, manifestUuid)
	ret0, _ := ret[0].(*Updates)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByAppIdManifestUuid indicates an expected call of FindOneByAppIdManifestUuid.
func (mr *MockUpdatesModelMockRecorder) FindOneByAppIdManifestUuid(ctx, appId, manifestUuid any) *MockUpdatesModelFindOneByAppIdManifestUuidCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByAppIdManifestUuid", reflect.TypeOf((*MockUpdatesModel)(nil).FindOneByAppIdManifestUuid), ctx, appId, manifestUuid)
	return &MockUpdatesModelFindOneByAppIdManifestUuidCall{Call: call}
}

// MockUpdatesModelFindOneByAppIdManifestUuidCall wrap *gomock.Call
type MockUpdatesModelFindOneByAppIdManifestUuidCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelFindOneByAppIdManifestUuidCall) Return(arg0 *Updates, arg1 error) *MockUpdatesModelFindOneByAppIdManifestUuidCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelFindOneByAppIdManifestUuidCall) Do(f func(context.Context, string, string) (*Updates, error)) *MockUpdatesModelFindOneByAppIdManifestUuidCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelFindOneByAppIdManifestUuidCall) DoAndReturn(f func(context.Context, string, string) (*Updates, error)) *MockUpdatesModelFindOneByAppIdManifestUuidCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockUpdatesModel) Insert(ctx context.Context, data *Updates) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockUpdatesModelMockRecorder) Insert(ctx, data any) *MockUpdatesModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockUpdatesModel)(nil).Insert), ctx, data)
	return &MockUpdatesModelInsertCall{Call: call}
}

// MockUpdatesModelInsertCall wrap *gomock.Call
type MockUpdatesModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockUpdatesModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelInsertCall) Do(f func(context.Context, *Updates) (sql.Result, error)) *MockUpdatesModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelInsertCall) DoAndReturn(f func(context.Context, *Updates) (sql.Result, error)) *MockUpdatesModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// InsertWithAssets mocks base method.
func (m *MockUpdatesModel) InsertWithAssets(ctx context.Context, data *Updates, assetRows []*UpdateAssets) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InsertWithAssets", ctx, data, assetRows)
	ret0, _ := ret[0].(error)
	return ret0
}

// InsertWithAssets indicates an expected call of InsertWithAssets.
func (mr *MockUpdatesModelMockRecorder) InsertWithAssets(ctx, data, assetRows any) *MockUpdatesModelInsertWithAssetsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InsertWithAssets", reflect.TypeOf((*MockUpdatesModel)(nil).InsertWithAssets), ctx, data, assetRows)
	return &MockUpdatesModelInsertWithAssetsCall{Call: call}
}

// MockUpdatesModelInsertWithAssetsCall wrap *gomock.Call
type MockUpdatesModelInsertWithAssetsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelInsertWithAssetsCall) Return(arg0 error) *MockUpdatesModelInsertWithAssetsCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelInsertWithAssetsCall) Do(f func(context.Context, *Updates, []*UpdateAssets) error) *MockUpdatesModelInsertWithAssetsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelInsertWithAssetsCall) DoAndReturn(f func(context.Context, *Updates, []*UpdateAssets) error) *MockUpdatesModelInsertWithAssetsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Publish mocks base method.
func (m *MockUpdatesModel) Publish(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockUpdatesModelMockRecorder) Publish(ctx, id any) *MockUpdatesModelPublishCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockUpdatesModel)(nil).Publish), ctx, id)
	return &MockUpdatesModelPublishCall{Call: call}
}

// MockUpdatesModelPublishCall wrap *gomock.Call
type MockUpdatesModelPublishCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelPublishCall) Return(arg0 int64, arg1 error) *MockUpdatesModelPublishCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelPublishCall) Do(f func(context.Context, string) (int64, error)) *MockUpdatesModelPublishCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelPublishCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockUpdatesModelPublishCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// PublishedRank mocks base method.
func (m *MockUpdatesModel) PublishedRank(ctx context.Context, id string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishedRank", ctx, id)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PublishedRank indicates an expected call of PublishedRank.
func (mr *MockUpdatesModelMockRecorder) PublishedRank(ctx, id any) *MockUpdatesModelPublishedRankCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishedRank", reflect.TypeOf((*MockUpdatesModel)(nil).PublishedRank), ctx, id)
	return &MockUpdatesModelPublishedRankCall{Call: call}
}

// MockUpdatesModelPublishedRankCall wrap *gomock.Call
type MockUpdatesModelPublishedRankCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelPublishedRankCall) Return(arg0 int64, arg1 error) *MockUpdatesModelPublishedRankCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelPublishedRankCall) Do(f func(context.Context, string) (int64, error)) *MockUpdatesModelPublishedRankCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelPublishedRankCall) DoAndReturn(f func(context.Context, string) (int64, error)) *MockUpdatesModelPublishedRankCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDelete mocks base method.
func (m *MockUpdatesModel) SoftDelete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDelete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDelete indicates an expected call of SoftDelete.
func (mr *MockUpdatesModelMockRecorder) SoftDelete(ctx, id any) *MockUpdatesModelSoftDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDelete", reflect.TypeOf((*MockUpdatesModel)(nil).SoftDelete), ctx, id)
	return &MockUpdatesModelSoftDeleteCall{Call: call}
}

// MockUpdatesModelSoftDeleteCall wrap *gomock.Call
type MockUpdatesModelSoftDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelSoftDeleteCall) Return(arg0 error) *MockUpdatesModelSoftDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelSoftDeleteCall) Do(f func(context.Context, string) error) *MockUpdatesModelSoftDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelSoftDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockUpdatesModelSoftDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SoftDeleteBeyondRank mocks base method.
func (m *MockUpdatesModel) SoftDeleteBeyondRank(ctx context.Context, appId string, keepLatestN int) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteBeyondRank", ctx, appId, keepLatestN)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SoftDeleteBeyondRank indicates an expected call of SoftDeleteBeyondRank.
func (mr *MockUpdatesModelMockRecorder) SoftDeleteBeyondRank(ctx, appId, keepLatestN any) *MockUpdatesModelSoftDeleteBeyondRankCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteBeyondRank", reflect.TypeOf((*MockUpdatesModel)(nil).SoftDeleteBeyondRank), ctx, appId, keepLatestN)
	return &MockUpdatesModelSoftDeleteBeyondRankCall{Call: call}
}

// MockUpdatesModelSoftDeleteBeyondRankCall wrap *gomock.Call
type MockUpdatesModelSoftDeleteBeyondRankCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelSoftDeleteBeyondRankCall) Return(arg0 []string, arg1 error) *MockUpdatesModelSoftDeleteBeyondRankCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelSoftDeleteBeyondRankCall) Do(f func(context.Context, string, int) ([]string, error)) *MockUpdatesModelSoftDeleteBeyondRankCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelSoftDeleteBeyondRankCall) DoAndReturn(f func(context.Context, string, int) ([]string, error)) *MockUpdatesModelSoftDeleteBeyondRankCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockUpdatesModel) Update(ctx context.Context, data *Updates) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUpdatesModelMockRecorder) Update(ctx, data any) *MockUpdatesModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUpdatesModel)(nil).Update), ctx, data)
	return &MockUpdatesModelUpdateCall{Call: call}
}

// MockUpdatesModelUpdateCall wrap *gomock.Call
type MockUpdatesModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelUpdateCall) Return(arg0 error) *MockUpdatesModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelUpdateCall) Do(f func(context.Context, *Updates) error) *MockUpdatesModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelUpdateCall) DoAndReturn(f func(context.Context, *Updates) error) *MockUpdatesModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockUpdatesModel) withSession(session sqlx.Session) UpdatesModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(UpdatesModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockUpdatesModelMockRecorder) withSession(session any) *MockUpdatesModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockUpdatesModel)(nil).withSession), session)
	return &MockUpdatesModelwithSessionCall{Call: call}
}

// MockUpdatesModelwithSessionCall wrap *gomock.Call
type MockUpdatesModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdatesModelwithSessionCall) Return(arg0 UpdatesModel) *MockUpdatesModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdatesModelwithSessionCall) Do(f func(sqlx.Session) UpdatesModel) *MockUpdatesModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdatesModelwithSessionCall) DoAndReturn(f func(sqlx.Session) UpdatesModel) *MockUpdatesModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
