// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	updatesFieldNames          = builder.RawFieldNames(&Updates{}, true)
	updatesRows                = strings.Join(updatesFieldNames, ",")
	updatesRowsExpectAutoSet   = strings.Join(stringx.Remove(updatesFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	updatesRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(updatesFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	updatesModel interface {
		Insert(ctx context.Context, data *Updates) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*Updates, error)
		FindOneByAppIdManifestUuid(ctx context.Context, appId string, manifestUuid string) (*Updates, error)
		Update(ctx context.Context, data *Updates) error
		Delete(ctx context.Context, id string) error
	}

	defaultUpdatesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Updates struct {
		Id               string         `db:"id"`
		AppId            string         `db:"app_id"`
		RuntimeVersionId string         `db:"runtime_version_id"`
		Platform         string         `db:"platform"`
		ManifestUuid     string         `db:"manifest_uuid"`
		LaunchAssetId    string         `db:"launch_asset_id"`
		Status           string         `db:"status"`
		Message          sql.NullString `db:"message"`
		GitCommitHash    sql.NullString `db:"git_commit_hash"`
		ManifestMetadata string         `db:"manifest_metadata"`
		Extra            string         `db:"extra"`
		ExpoConfig       sql.NullString `db:"expo_config"`
		ManifestSnapshot string         `db:"manifest_snapshot"`
		RolledBackFrom   sql.NullString `db:"rolled_back_from"`
		CreatedAt        time.Time      `db:"created_at"`
		PublishedAt      sql.NullTime   `db:"published_at"`
		DeletedAt        sql.NullTime   `db:"deleted_at"`
	}
)

func newUpdatesModel(conn sqlx.SqlConn) *defaultUpdatesModel {
	return &defaultUpdatesModel{
		conn:  conn,
		table: `"public"."updates"`,
	}
}

func (m *defaultUpdatesModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUpdatesModel) FindOne(ctx context.Context, id string) (*Updates, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", updatesRows, m.table)
	var resp Updates
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUpdatesModel) FindOneByAppIdManifestUuid(ctx context.Context, appId string, manifestUuid string) (*Updates, error) {
	var resp Updates
	query := fmt.Sprintf("select %s from %s where app_id = $1 and manifest_uuid = $2 limit 1", updatesRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, appId, manifestUuid)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUpdatesModel) Insert(ctx context.Context, data *Updates) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)", m.table, updatesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.AppId, data.RuntimeVersionId, data.Platform, data.ManifestUuid, data.LaunchAssetId, data.Status, data.Message, data.GitCommitHash, data.ManifestMetadata, data.Extra, data.ExpoConfig, data.ManifestSnapshot, data.RolledBackFrom, data.PublishedAt, data.DeletedAt)
	return ret, err
}

func (m *defaultUpdatesModel) Update(ctx context.Context, newData *Updates) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, updatesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.AppId, newData.RuntimeVersionId, newData.Platform, newData.ManifestUuid, newData.LaunchAssetId, newData.Status, newData.Message, newData.GitCommitHash, newData.ManifestMetadata, newData.Extra, newData.ExpoConfig, newData.ManifestSnapshot, newData.RolledBackFrom, newData.PublishedAt, newData.DeletedAt)
	return err
}

func (m *defaultUpdatesModel) tableName() string {
	return m.table
}
