// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/updateassetsmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/updateassetsmodel.go -destination=db/models/updateassetsmodel_mock.go -package=models -aux_files=models=db/models/updateassetsmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockUpdateAssetsModel is a mock of UpdateAssetsModel interface.
type MockUpdateAssetsModel struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateAssetsModelMockRecorder
	isgomock struct{}
}

// MockUpdateAssetsModelMockRecorder is the mock recorder for MockUpdateAssetsModel.
type MockUpdateAssetsModelMockRecorder struct {
	mock *MockUpdateAssetsModel
}

// NewMockUpdateAssetsModel creates a new mock instance.
func NewMockUpdateAssetsModel(ctrl *gomock.Controller) *MockUpdateAssetsModel {
	mock := &MockUpdateAssetsModel{ctrl: ctrl}
	mock.recorder = &MockUpdateAssetsModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateAssetsModel) EXPECT() *MockUpdateAssetsModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUpdateAssetsModel) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUpdateAssetsModelMockRecorder) Delete(ctx, id any) *MockUpdateAssetsModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUpdateAssetsModel)(nil).Delete), ctx, id)
	return &MockUpdateAssetsModelDeleteCall{Call: call}
}

// MockUpdateAssetsModelDeleteCall wrap *gomock.Call
type MockUpdateAssetsModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdateAssetsModelDeleteCall) Return(arg0 error) *MockUpdateAssetsModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdateAssetsModelDeleteCall) Do(f func(context.Context, string) error) *MockUpdateAssetsModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdateAssetsModelDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockUpdateAssetsModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindAllByUpdateId mocks base method.
func (m *MockUpdateAssetsModel) FindAllByUpdateId(ctx context.Context, updateId string) ([]*UpdateAssets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllByUpdateId", ctx, updateId)
	ret0, _ := ret[0].([]*UpdateAssets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllByUpdateId indicates an expected call of FindAllByUpdateId.
func (mr *MockUpdateAssetsModelMockRecorder) FindAllByUpdateId(ctx, updateId any) *MockUpdateAssetsModelFindAllByUpdateIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllByUpdateId", reflect.TypeOf((*MockUpdateAssetsModel)(nil).FindAllByUpdateId), ctx, updateId)
	return &MockUpdateAssetsModelFindAllByUpdateIdCall{Call: call}
}

// MockUpdateAssetsModelFindAllByUpdateIdCall wrap *gomock.Call
type MockUpdateAssetsModelFindAllByUpdateIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdateAssetsModelFindAllByUpdateIdCall) Return(arg0 []*UpdateAssets, arg1 error) *MockUpdateAssetsModelFindAllByUpdateIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdateAssetsModelFindAllByUpdateIdCall) Do(f func(context.Context, string) ([]*UpdateAssets, error)) *MockUpdateAssetsModelFindAllByUpdateIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdateAssetsModelFindAllByUpdateIdCall) DoAndReturn(f func(context.Context, string) ([]*UpdateAssets, error)) *MockUpdateAssetsModelFindAllByUpdateIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockUpdateAssetsModel) FindOne(ctx context.Context, id string) (*UpdateAssets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*UpdateAssets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockUpdateAssetsModelMockRecorder) FindOne(ctx, id any) *MockUpdateAssetsModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockUpdateAssetsModel)(nil).FindOne), ctx, id)
	return &MockUpdateAssetsModelFindOneCall{Call: call}
}

// MockUpdateAssetsModelFindOneCall wrap *gomock.Call
type MockUpdateAssetsModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdateAssetsModelFindOneCall) Return(arg0 *UpdateAssets, arg1 error) *MockUpdateAssetsModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdateAssetsModelFindOneCall) Do(f func(context.Context, string) (*UpdateAssets, error)) *MockUpdateAssetsModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdateAssetsModelFindOneCall) DoAndReturn(f func(context.Context, string) (*UpdateAssets, error)) *MockUpdateAssetsModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByUpdateIdAssetKey mocks base method.
func (m *MockUpdateAssetsModel) FindOneByUpdateIdAssetKey(ctx context.Context, updateId, assetKey string) (*UpdateAssets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUpdateIdAssetKey", ctx, updateId, assetKey)
	ret0, _ := ret[0].(*UpdateAssets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUpdateIdAssetKey indicates an expected call of FindOneByUpdateIdAssetKey.
func (mr *MockUpdateAssetsModelMockRecorder) FindOneByUpdateIdAssetKey(ctx, updateId, assetKey any) *MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUpdateIdAssetKey", reflect.TypeOf((*MockUpdateAssetsModel)(nil).FindOneByUpdateIdAssetKey), ctx, updateId, assetKey)
	return &MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall{Call: call}
}

// MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall wrap *gomock.Call
type MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall) Return(arg0 *UpdateAssets, arg1 error) *MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall) Do(f func(context.Context, string, string) (*UpdateAssets, error)) *MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall) DoAndReturn(f func(context.Context, string, string) (*UpdateAssets, error)) *MockUpdateAssetsModelFindOneByUpdateIdAssetKeyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockUpdateAssetsModel) Insert(ctx context.Context, data *UpdateAssets) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockUpdateAssetsModelMockRecorder) Insert(ctx, data any) *MockUpdateAssetsModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockUpdateAssetsModel)(nil).Insert), ctx, data)
	return &MockUpdateAssetsModelInsertCall{Call: call}
}

// MockUpdateAssetsModelInsertCall wrap *gomock.Call
type MockUpdateAssetsModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdateAssetsModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockUpdateAssetsModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdateAssetsModelInsertCall) Do(f func(context.Context, *UpdateAssets) (sql.Result, error)) *MockUpdateAssetsModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdateAssetsModelInsertCall) DoAndReturn(f func(context.Context, *UpdateAssets) (sql.Result, error)) *MockUpdateAssetsModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockUpdateAssetsModel) Update(ctx context.Context, data *UpdateAssets) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUpdateAssetsModelMockRecorder) Update(ctx, data any) *MockUpdateAssetsModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUpdateAssetsModel)(nil).Update), ctx, data)
	return &MockUpdateAssetsModelUpdateCall{Call: call}
}

// MockUpdateAssetsModelUpdateCall wrap *gomock.Call
type MockUpdateAssetsModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdateAssetsModelUpdateCall) Return(arg0 error) *MockUpdateAssetsModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdateAssetsModelUpdateCall) Do(f func(context.Context, *UpdateAssets) error) *MockUpdateAssetsModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdateAssetsModelUpdateCall) DoAndReturn(f func(context.Context, *UpdateAssets) error) *MockUpdateAssetsModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockUpdateAssetsModel) withSession(session sqlx.Session) UpdateAssetsModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(UpdateAssetsModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockUpdateAssetsModelMockRecorder) withSession(session any) *MockUpdateAssetsModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockUpdateAssetsModel)(nil).withSession), session)
	return &MockUpdateAssetsModelwithSessionCall{Call: call}
}

// MockUpdateAssetsModelwithSessionCall wrap *gomock.Call
type MockUpdateAssetsModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUpdateAssetsModelwithSessionCall) Return(arg0 UpdateAssetsModel) *MockUpdateAssetsModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUpdateAssetsModelwithSessionCall) Do(f func(sqlx.Session) UpdateAssetsModel) *MockUpdateAssetsModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUpdateAssetsModelwithSessionCall) DoAndReturn(f func(sqlx.Session) UpdateAssetsModel) *MockUpdateAssetsModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
