// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.1

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	updateAssetsFieldNames          = builder.RawFieldNames(&UpdateAssets{}, true)
	updateAssetsRows                = strings.Join(updateAssetsFieldNames, ",")
	updateAssetsRowsExpectAutoSet   = strings.Join(stringx.Remove(updateAssetsFieldNames, "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"), ",")
	updateAssetsRowsWithPlaceHolder = builder.PostgreSqlJoin(stringx.Remove(updateAssetsFieldNames, "id", "create_at", "create_time", "created_at", "update_at", "update_time", "updated_at"))
)

type (
	updateAssetsModel interface {
		Insert(ctx context.Context, data *UpdateAssets) (sql.Result, error)
		FindOne(ctx context.Context, id string) (*UpdateAssets, error)
		FindOneByUpdateIdAssetKey(ctx context.Context, updateId string, assetKey string) (*UpdateAssets, error)
		Update(ctx context.Context, data *UpdateAssets) error
		Delete(ctx context.Context, id string) error
	}

	defaultUpdateAssetsModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UpdateAssets struct {
		Id        string         `db:"id"`
		UpdateId  string         `db:"update_id"`
		AssetId   string         `db:"asset_id"`
		AssetKey  string         `db:"asset_key"`
		FileExt   sql.NullString `db:"file_ext"`
		SortOrder int64          `db:"sort_order"`
	}
)

func newUpdateAssetsModel(conn sqlx.SqlConn) *defaultUpdateAssetsModel {
	return &defaultUpdateAssetsModel{
		conn:  conn,
		table: `"public"."update_assets"`,
	}
}

func (m *defaultUpdateAssetsModel) Delete(ctx context.Context, id string) error {
	query := fmt.Sprintf("delete from %s where id = $1", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUpdateAssetsModel) FindOne(ctx context.Context, id string) (*UpdateAssets, error) {
	query := fmt.Sprintf("select %s from %s where id = $1 limit 1", updateAssetsRows, m.table)
	var resp UpdateAssets
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUpdateAssetsModel) FindOneByUpdateIdAssetKey(ctx context.Context, updateId string, assetKey string) (*UpdateAssets, error) {
	var resp UpdateAssets
	query := fmt.Sprintf("select %s from %s where update_id = $1 and asset_key = $2 limit 1", updateAssetsRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, updateId, assetKey)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUpdateAssetsModel) Insert(ctx context.Context, data *UpdateAssets) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values ($1, $2, $3, $4, $5, $6)", m.table, updateAssetsRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.UpdateId, data.AssetId, data.AssetKey, data.FileExt, data.SortOrder)
	return ret, err
}

func (m *defaultUpdateAssetsModel) Update(ctx context.Context, newData *UpdateAssets) error {
	query := fmt.Sprintf("update %s set %s where id = $1", m.table, updateAssetsRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.Id, newData.UpdateId, newData.AssetId, newData.AssetKey, newData.FileExt, newData.SortOrder)
	return err
}

func (m *defaultUpdateAssetsModel) tableName() string {
	return m.table
}
