// Code generated by MockGen. DO NOT EDIT.
// Source: db/models/usersmodel.go
//
// Generated by this command:
//
//	mockgen -source=db/models/usersmodel.go -destination=db/models/usersmodel_mock.go -package=models -aux_files=models=db/models/usersmodel_gen.go -self_package=github.com/hoywu/expo-ota/server/db/models -typed
//

// Package models is a generated GoMock package.
package models

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	sqlx "github.com/zeromicro/go-zero/core/stores/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockUsersModel is a mock of UsersModel interface.
type MockUsersModel struct {
	ctrl     *gomock.Controller
	recorder *MockUsersModelMockRecorder
	isgomock struct{}
}

// MockUsersModelMockRecorder is the mock recorder for MockUsersModel.
type MockUsersModelMockRecorder struct {
	mock *MockUsersModel
}

// NewMockUsersModel creates a new mock instance.
func NewMockUsersModel(ctrl *gomock.Controller) *MockUsersModel {
	mock := &MockUsersModel{ctrl: ctrl}
	mock.recorder = &MockUsersModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsersModel) EXPECT() *MockUsersModelMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockUsersModel) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsersModelMockRecorder) Delete(ctx, id any) *MockUsersModelDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsersModel)(nil).Delete), ctx, id)
	return &MockUsersModelDeleteCall{Call: call}
}

// MockUsersModelDeleteCall wrap *gomock.Call
type MockUsersModelDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUsersModelDeleteCall) Return(arg0 error) *MockUsersModelDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUsersModelDeleteCall) Do(f func(context.Context, string) error) *MockUsersModelDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUsersModelDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockUsersModelDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindAll mocks base method.
func (m *MockUsersModel) FindAll(ctx context.Context) ([]*Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx)
	ret0, _ := ret[0].([]*Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockUsersModelMockRecorder) FindAll(ctx any) *MockUsersModelFindAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockUsersModel)(nil).FindAll), ctx)
	return &MockUsersModelFindAllCall{Call: call}
}

// MockUsersModelFindAllCall wrap *gomock.Call
type MockUsersModelFindAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUsersModelFindAllCall) Return(arg0 []*Users, arg1 error) *MockUsersModelFindAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUsersModelFindAllCall) Do(f func(context.Context) ([]*Users, error)) *MockUsersModelFindAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUsersModelFindAllCall) DoAndReturn(f func(context.Context) ([]*Users, error)) *MockUsersModelFindAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOne mocks base method.
func (m *MockUsersModel) FindOne(ctx context.Context, id string) (*Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOne", ctx, id)
	ret0, _ := ret[0].(*Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOne indicates an expected call of FindOne.
func (mr *MockUsersModelMockRecorder) FindOne(ctx, id any) *MockUsersModelFindOneCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOne", reflect.TypeOf((*MockUsersModel)(nil).FindOne), ctx, id)
	return &MockUsersModelFindOneCall{Call: call}
}

// MockUsersModelFindOneCall wrap *gomock.Call
type MockUsersModelFindOneCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUsersModelFindOneCall) Return(arg0 *Users, arg1 error) *MockUsersModelFindOneCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUsersModelFindOneCall) Do(f func(context.Context, string) (*Users, error)) *MockUsersModelFindOneCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUsersModelFindOneCall) DoAndReturn(f func(context.Context, string) (*Users, error)) *MockUsersModelFindOneCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// FindOneByUsername mocks base method.
func (m *MockUsersModel) FindOneByUsername(ctx context.Context, username string) (*Users, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindOneByUsername", ctx, username)
	ret0, _ := ret[0].(*Users)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindOneByUsername indicates an expected call of FindOneByUsername.
func (mr *MockUsersModelMockRecorder) FindOneByUsername(ctx, username any) *MockUsersModelFindOneByUsernameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindOneByUsername", reflect.TypeOf((*MockUsersModel)(nil).FindOneByUsername), ctx, username)
	return &MockUsersModelFindOneByUsernameCall{Call: call}
}

// MockUsersModelFindOneByUsernameCall wrap *gomock.Call
type MockUsersModelFindOneByUsernameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUsersModelFindOneByUsernameCall) Return(arg0 *Users, arg1 error) *MockUsersModelFindOneByUsernameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUsersModelFindOneByUsernameCall) Do(f func(context.Context, string) (*Users, error)) *MockUsersModelFindOneByUsernameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUsersModelFindOneByUsernameCall) DoAndReturn(f func(context.Context, string) (*Users, error)) *MockUsersModelFindOneByUsernameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Insert mocks base method.
func (m *MockUsersModel) Insert(ctx context.Context, data *Users) (sql.Result, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", ctx, data)
	ret0, _ := ret[0].(sql.Result)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Insert indicates an expected call of Insert.
func (mr *MockUsersModelMockRecorder) Insert(ctx, data any) *MockUsersModelInsertCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockUsersModel)(nil).Insert), ctx, data)
	return &MockUsersModelInsertCall{Call: call}
}

// MockUsersModelInsertCall wrap *gomock.Call
type MockUsersModelInsertCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUsersModelInsertCall) Return(arg0 sql.Result, arg1 error) *MockUsersModelInsertCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUsersModelInsertCall) Do(f func(context.Context, *Users) (sql.Result, error)) *MockUsersModelInsertCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUsersModelInsertCall) DoAndReturn(f func(context.Context, *Users) (sql.Result, error)) *MockUsersModelInsertCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockUsersModel) Update(ctx context.Context, data *Users) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUsersModelMockRecorder) Update(ctx, data any) *MockUsersModelUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsersModel)(nil).Update), ctx, data)
	return &MockUsersModelUpdateCall{Call: call}
}

// MockUsersModelUpdateCall wrap *gomock.Call
type MockUsersModelUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUsersModelUpdateCall) Return(arg0 error) *MockUsersModelUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUsersModelUpdateCall) Do(f func(context.Context, *Users) error) *MockUsersModelUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUsersModelUpdateCall) DoAndReturn(f func(context.Context, *Users) error) *MockUsersModelUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// withSession mocks base method.
func (m *MockUsersModel) withSession(session sqlx.Session) UsersModel {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "withSession", session)
	ret0, _ := ret[0].(UsersModel)
	return ret0
}

// withSession indicates an expected call of withSession.
func (mr *MockUsersModelMockRecorder) withSession(session any) *MockUsersModelwithSessionCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "withSession", reflect.TypeOf((*MockUsersModel)(nil).withSession), session)
	return &MockUsersModelwithSessionCall{Call: call}
}

// MockUsersModelwithSessionCall wrap *gomock.Call
type MockUsersModelwithSessionCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockUsersModelwithSessionCall) Return(arg0 UsersModel) *MockUsersModelwithSessionCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockUsersModelwithSessionCall) Do(f func(sqlx.Session) UsersModel) *MockUsersModelwithSessionCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockUsersModelwithSessionCall) DoAndReturn(f func(sqlx.Session) UsersModel) *MockUsersModelwithSessionCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
